import { BitcoinIcon, DogecoinIcon, EthereumIcon } from "@/components/icons";
import { CryptoCurrency, MutualFund, NewsArticle, CryptoETF } from "./types";
import { Coins, Package } from "lucide-react";

const USD_TO_INR = 90;

const generatePriceHistory = (base: number, days = 365) => {
  const history = [];
  let currentPrice = base;
  for (let i = 0; i < days; i++) {
    const date = new Date(Date.now() - (days - 1 - i) * 24 * 60 * 60 * 1000);
    // Add hourly fluctuations for the last day
    if (i === days - 1) {
      let hourlyPrice = history[history.length - 1]?.value || base * (1 + (Math.random() - 0.5) * 0.1);
      for (let j = 0; j < 24; j++) {
        history.push({
          time: new Date(date.getTime() - (23 - j) * 60 * 60 * 1000).toISOString(),
          value: hourlyPrice,
        });
        hourlyPrice *= (1 + (Math.random() - 0.49) * 0.02); // Tighter fluctuation for hours
      }
    } else {
       history.push({
        time: date.toISOString(),
        value: currentPrice,
      });
      currentPrice *= (1 + (Math.random() - 0.49) * 0.1); // Fluctuate by up to 10% daily
    }
  }
  return history;
};


export const INITIAL_CRYPTO_DATA: CryptoCurrency[] = [
  {
    id: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    icon: BitcoinIcon,
    price: 68134.32 * USD_TO_INR,
    change24h: 2.5,
    volume24h: 34500000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(68134.32 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    icon: EthereumIcon,
    price: 3567.89 * USD_TO_INR,
    change24h: -1.2,
    volume24h: 18200000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(3567.89 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'tether',
    name: 'Tether',
    symbol: 'USDT',
    icon: Coins,
    price: 1.00 * USD_TO_INR,
    change24h: 0.00,
    volume24h: 50000000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(1.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'binancecoin',
    name: 'BNB',
    symbol: 'BNB',
    icon: Coins,
    price: 570.00 * USD_TO_INR,
    change24h: 0.89,
    volume24h: 1500000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(570.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'usd-coin',
    name: 'USD Coin',
    symbol: 'USDC',
    icon: Coins,
    price: 1.00 * USD_TO_INR,
    change24h: 0.00,
    volume24h: 5000000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(1.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "cardano",
    name: "Cardano",
    symbol: "ADA",
    icon: Coins,
    price: 0.38 * USD_TO_INR,
    change24h: -2.17,
    volume24h: 350000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.38 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "solana",
    name: "Solana",
    symbol: "SOL",
    icon: Coins,
    price: 150.0 * USD_TO_INR,
    change24h: 5.5,
    volume24h: 2000000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(150.0 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "ripple",
    name: "XRP",
    symbol: "XRP",
    icon: Coins,
    price: 0.47 * USD_TO_INR,
    change24h: 2.13,
    volume24h: 1200000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.47 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'terra-luna',
    name: 'Terra',
    symbol: 'LUNA',
    icon: Coins,
    price: 0.43 * USD_TO_INR,
    change24h: 1.5,
    volume24h: 30000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.43 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'polkadot',
    name: 'Polkadot',
    symbol: 'DOT',
    icon: Coins,
    price: 5.88 * USD_TO_INR,
    change24h: 3.1,
    volume24h: 200000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(5.88 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "dogecoin",
    name: "Dogecoin",
    symbol: "DOGE",
    icon: DogecoinIcon,
    price: 0.12 * USD_TO_INR,
    change24h: 5.8,
    volume24h: 2100000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.12 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'avalanche-2',
    name: 'Avalanche',
    symbol: 'AVAX',
    icon: Coins,
    price: 25.45 * USD_TO_INR,
    change24h: 4.2,
    volume24h: 400000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(25.45 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'binance-usd',
    name: 'Binance USD',
    symbol: 'BUSD',
    icon: Coins,
    price: 1.00 * USD_TO_INR,
    change24h: 0.0,
    volume24h: 3000000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(1.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'matic-network',
    name: 'Polygon',
    symbol: 'MATIC',
    icon: Coins,
    price: 0.57 * USD_TO_INR,
    change24h: 2.8,
    volume24h: 300000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.57 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "shiba-inu",
    name: "Shiba Inu",
    symbol: "SHIB",
    icon: Coins,
    price: 0.000017 * USD_TO_INR,
    change24h: 3.7,
    volume24h: 300000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.000017 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'terrausd',
    name: 'TerraUSD',
    symbol: 'UST',
    icon: Coins,
    price: 0.018 * USD_TO_INR,
    change24h: -1.0,
    volume24h: 10000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.018 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'crypto-com-chain',
    name: 'Crypto.com Coin',
    symbol: 'CRO',
    icon: Coins,
    price: 0.09 * USD_TO_INR,
    change24h: 1.2,
    volume24h: 15000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.09 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'wrapped-bitcoin',
    name: 'Wrapped Bitcoin',
    symbol: 'WBTC',
    icon: Coins,
    price: 68130.00 * USD_TO_INR,
    change24h: 2.5,
    volume24h: 200000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(68130.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'dai',
    name: 'Dai',
    symbol: 'DAI',
    icon: Coins,
    price: 1.00 * USD_TO_INR,
    change24h: 0.0,
    volume24h: 400000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(1.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'cosmos',
    name: 'Cosmos',
    symbol: 'ATOM',
    icon: Coins,
    price: 6.95 * USD_TO_INR,
    change24h: 3.5,
    volume24h: 150000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(6.95 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'ftx-token',
    name: 'FTX Token',
    symbol: 'FTT',
    icon: Coins,
    price: 1.45 * USD_TO_INR,
    change24h: -0.5,
    volume24h: 20000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(1.45 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "tron",
    name: "TRON",
    symbol: "TRX",
    icon: Coins,
    price: 0.11 * USD_TO_INR,
    change24h: 2.56,
    volume24h: 400000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.11 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'bitcoin-cash',
    name: 'Bitcoin Cash',
    symbol: 'BCH',
    icon: Coins,
    price: 388.0 * USD_TO_INR,
    change24h: 1.8,
    volume24h: 300000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(388.0 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'fantom',
    name: 'Fantom',
    symbol: 'FTM',
    icon: Coins,
    price: 0.60 * USD_TO_INR,
    change24h: 7.2,
    volume24h: 150000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.60 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'stellar',
    name: 'Stellar',
    symbol: 'XLM',
    icon: Coins,
    price: 0.09 * USD_TO_INR,
    change24h: 1.1,
    volume24h: 70000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.09 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "decentraland",
    name: "Decentraland",
    symbol: "MANA",
    icon: Coins,
    price: 0.33 * USD_TO_INR,
    change24h: 2.5,
    volume24h: 45000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.33 * USD_TO_INR),
    assetType: 'Web3',
  },
  {
    id: 'hedera-hashgraph',
    name: 'Hedera',
    symbol: 'HBAR',
    icon: Coins,
    price: 0.078 * USD_TO_INR,
    change24h: 4.8,
    volume24h: 50000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.078 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'bitcoin-bep2',
    name: 'Bitcoin BEP2',
    symbol: 'BTCB',
    icon: Coins,
    price: 68100.0 * USD_TO_INR,
    change24h: 2.4,
    volume24h: 10000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(68100.0 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'internet-computer',
    name: 'Internet Computer',
    symbol: 'ICP',
    icon: Coins,
    price: 8.30 * USD_TO_INR,
    change24h: 6.1,
    volume24h: 100000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(8.30 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'unus-sed-leo',
    name: 'UNUS SED LEO',
    symbol: 'LEO',
    icon: Coins,
    price: 5.75 * USD_TO_INR,
    change24h: 0.1,
    volume24h: 2000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(5.75 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "the-sandbox",
    name: "The Sandbox",
    symbol: "SAND",
    icon: Coins,
    price: 0.33 * USD_TO_INR,
    change24h: 3.1,
    volume24h: 60000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.33 * USD_TO_INR),
    assetType: 'Web3',
  },
  {
    id: 'ethereum-classic',
    name: 'Ethereum Classic',
    symbol: 'ETC',
    icon: Coins,
    price: 23.50 * USD_TO_INR,
    change24h: 1.5,
    volume24h: 200000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(23.50 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'vechain',
    name: 'VeChain',
    symbol: 'VET',
    icon: Coins,
    price: 0.026 * USD_TO_INR,
    change24h: 3.9,
    volume24h: 50000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.026 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'tezos',
    name: 'Tezos',
    symbol: 'XTZ',
    icon: Coins,
    price: 0.78 * USD_TO_INR,
    change24h: 2.2,
    volume24h: 30000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.78 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'axie-infinity',
    name: 'Axie Infinity',
    symbol: 'AXS',
    icon: Coins,
    price: 6.20 * USD_TO_INR,
    change24h: 5.5,
    volume24h: 80000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(6.20 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'filecoin',
    name: 'Filecoin',
    symbol: 'FIL',
    icon: Coins,
    price: 4.40 * USD_TO_INR,
    change24h: 4.1,
    volume24h: 150000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(4.40 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'elrond-erd-2',
    name: 'Elrond',
    symbol: 'EGLD',
    icon: Coins,
    price: 30.00 * USD_TO_INR,
    change24h: 6.8,
    volume24h: 50000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(30.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'klay-token',
    name: 'Klaytn',
    symbol: 'KLAY',
    icon: Coins,
    price: 0.16 * USD_TO_INR,
    change24h: 1.9,
    volume24h: 20000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.16 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'helium',
    name: 'Helium',
    symbol: 'HNT',
    icon: Coins,
    price: 3.40 * USD_TO_INR,
    change24h: 8.2,
    volume24h: 15000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(3.40 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'theta-token',
    name: 'Theta Network',
    symbol: 'THETA',
    icon: Coins,
    price: 1.60 * USD_TO_INR,
    change24h: 7.5,
    volume24h: 60000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(1.60 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'maker',
    name: 'Maker',
    symbol: 'MKR',
    icon: Coins,
    price: 2375.00 * USD_TO_INR,
    change24h: 0.5,
    volume24h: 90000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(2375.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'flow',
    name: 'Flow',
    symbol: 'FLOW',
    icon: Coins,
    price: 0.64 * USD_TO_INR,
    change24h: 4.3,
    volume24h: 40000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.64 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'the-graph',
    name: 'The Graph',
    symbol: 'GRT',
    icon: Coins,
    price: 0.22 * USD_TO_INR,
    change24h: 9.9,
    volume24h: 100000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.22 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'pancakeswap-token',
    name: 'PancakeSwap',
    symbol: 'CAKE',
    icon: Coins,
    price: 2.2 * USD_TO_INR,
    change24h: 1.8,
    volume24h: 40000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(2.2 * USD_TO_INR),
    assetType: 'Web3',
  },
  {
    id: 'bittorrent-2',
    name: 'BitTorrent (New)',
    symbol: 'BTT',
    icon: Coins,
    price: 0.00000088 * USD_TO_INR,
    change24h: 2.1,
    volume24h: 300000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.00000088 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'stacks',
    name: 'Stacks',
    symbol: 'STX',
    icon: Coins,
    price: 2.05 * USD_TO_INR,
    change24h: 10.5,
    volume24h: 120000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(2.05 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'bitcoin-sv',
    name: 'Bitcoin SV',
    symbol: 'BSV',
    icon: Coins,
    price: 45.50 * USD_TO_INR,
    change24h: -2.5,
    volume24h: 40000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(45.50 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'curve-dao-token',
    name: 'Curve DAO Token',
    symbol: 'CRV',
    icon: Coins,
    price: 0.34 * USD_TO_INR,
    change24h: 15.2,
    volume24h: 80000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.34 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'enjincoin',
    name: 'Enjin Coin',
    symbol: 'ENJ',
    icon: Coins,
    price: 0.20 * USD_TO_INR,
    change24h: 6.3,
    volume24h: 25000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.20 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'true-usd',
    name: 'TrueUSD',
    symbol: 'TUSD',
    icon: Coins,
    price: 0.99 * USD_TO_INR,
    change24h: -0.1,
    volume24h: 50000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.99 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'kucoin-shares',
    name: 'KuCoin Token',
    symbol: 'KCS',
    icon: Coins,
    price: 9.80 * USD_TO_INR,
    change24h: 0.8,
    volume24h: 1000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(9.80 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'kusama',
    name: 'Kusama',
    symbol: 'KSM',
    icon: Coins,
    price: 24.00 * USD_TO_INR,
    change24h: 3.2,
    volume24h: 15000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(24.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'ecash',
    name: 'eCash',
    symbol: 'XEC',
    icon: Coins,
    price: 0.000032 * USD_TO_INR,
    change24h: 5.1,
    volume24h: 20000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.000032 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'huobi-token',
    name: 'Huobi Token',
    symbol: 'HT',
    icon: Coins,
    price: 0.52 * USD_TO_INR,
    change24h: -1.2,
    volume24h: 5000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.52 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'neo',
    name: 'Neo',
    symbol: 'NEO',
    icon: Coins,
    price: 11.40 * USD_TO_INR,
    change24h: 4.5,
    volume24h: 40000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(11.40 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'gala',
    name: 'Gala',
    symbol: 'GALA',
    icon: Coins,
    price: 0.028 * USD_TO_INR,
    change24h: 8.8,
    volume24h: 90000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.028 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'thorchain',
    name: 'THORChain',
    symbol: 'RUNE',
    icon: Coins,
    price: 4.15 * USD_TO_INR,
    change24h: 7.1,
    volume24h: 180000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(4.15 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'arweave',
    name: 'Arweave',
    symbol: 'AR',
    icon: Coins,
    price: 29.00 * USD_TO_INR,
    change24h: 12.3,
    volume24h: 70000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(29.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'convex-finance',
    name: 'Convex Finance',
    symbol: 'CVX',
    icon: Coins,
    price: 3.00 * USD_TO_INR,
    change24h: -3.5,
    volume24h: 5000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(3.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'zcash',
    name: 'Zcash',
    symbol: 'ZEC',
    icon: Coins,
    price: 20.20 * USD_TO_INR,
    change24h: 1.1,
    volume24h: 30000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(20.20 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'quant-network',
    name: 'Quant',
    symbol: 'QNT',
    icon: Coins,
    price: 76.00 * USD_TO_INR,
    change24h: 2.8,
    volume24h: 20000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(76.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'oasis-network',
    name: 'Oasis Network',
    symbol: 'ROSE',
    icon: Coins,
    price: 0.09 * USD_TO_INR,
    change24h: 6.7,
    volume24h: 25000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.09 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'nexo',
    name: 'NEXO',
    symbol: 'NEXO',
    icon: Coins,
    price: 1.19 * USD_TO_INR,
    change24h: 0.5,
    volume24h: 5000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(1.19 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'chiliz',
    name: 'Chiliz',
    symbol: 'CHZ',
    icon: Coins,
    price: 0.08 * USD_TO_INR,
    change24h: 11.2,
    volume24h: 90000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.08 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'symbol',
    name: 'Symbol',
    symbol: 'XYM',
    icon: Coins,
    price: 0.02 * USD_TO_INR,
    change24h: 1.3,
    volume24h: 1000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.02 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'kadena',
    name: 'Kadena',
    symbol: 'KDA',
    icon: Coins,
    price: 0.58 * USD_TO_INR,
    change24h: 3.3,
    volume24h: 5000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.58 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'dash',
    name: 'Dash',
    symbol: 'DASH',
    icon: Coins,
    price: 24.00 * USD_TO_INR,
    change24h: 2.1,
    volume24h: 40000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(24.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'waves',
    name: 'Waves',
    symbol: 'WAVES',
    icon: Coins,
    price: 2.40 * USD_TO_INR,
    change24h: 13.5,
    volume24h: 150000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(2.40 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'paxos-standard',
    name: 'Pax Dollar',
    symbol: 'USDP',
    icon: Coins,
    price: 1.00 * USD_TO_INR,
    change24h: 0.0,
    volume24h: 5000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(1.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'mina-protocol',
    name: 'Mina',
    symbol: 'MINA',
    icon: Coins,
    price: 0.54 * USD_TO_INR,
    change24h: 7.9,
    volume24h: 30000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.54 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'nem',
    name: 'NEM',
    symbol: 'XEM',
    icon: Coins,
    price: 0.015 * USD_TO_INR,
    change24h: -2.1,
    volume24h: 2000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.015 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'theta-fuel',
    name: 'Theta Fuel',
    symbol: 'TFUEL',
    icon: Coins,
    price: 0.076 * USD_TO_INR,
    change24h: 5.8,
    volume24h: 20000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.076 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'yearn-finance',
    name: 'yearn.finance',
    symbol: 'YFI',
    icon: Coins,
    price: 5850.00 * USD_TO_INR,
    change24h: 1.2,
    volume24h: 25000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(5850.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'bora',
    name: 'BORA',
    symbol: 'BORA',
    icon: Coins,
    price: 0.10 * USD_TO_INR,
    change24h: 0.9,
    volume24h: 1000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.10 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'decred',
    name: 'Decred',
    symbol: 'DCR',
    icon: Coins,
    price: 16.00 * USD_TO_INR,
    change24h: -0.5,
    volume24h: 2000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(16.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'compound-governance-token',
    name: 'Compound',
    symbol: 'COMP',
    icon: Coins,
    price: 49.00 * USD_TO_INR,
    change24h: 3.9,
    volume24h: 40000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(49.00 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'secret',
    name: 'Secret',
    symbol: 'SCRT',
    icon: Coins,
    price: 0.31 * USD_TO_INR,
    change24h: 4.1,
    volume24h: 3000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.31 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'holotoken',
    name: 'Holo',
    symbol: 'HOT',
    icon: Coins,
    price: 0.0018 * USD_TO_INR,
    change24h: 2.7,
    volume24h: 15000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.0018 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: '1inch',
    name: '1inch',
    symbol: '1INCH',
    icon: Coins,
    price: 0.40 * USD_TO_INR,
    change24h: 8.1,
    volume24h: 40000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.40 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: 'render-token',
    name: 'Render Token',
    symbol: 'RNDR',
    icon: Coins,
    price: 7.70 * USD_TO_INR,
    change24h: 9.5,
    volume24h: 200000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(7.70 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "notcoin",
    name: "Notcoin",
    symbol: "NOT",
    icon: Coins,
    price: 0.015 * USD_TO_INR,
    change24h: 25.00,
    volume24h: 1000000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.015 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "pepe",
    name: "Pepe",
    symbol: "PEPE",
    icon: Coins,
    price: 0.000011 * USD_TO_INR,
    change24h: 18.87,
    volume24h: 800000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.000011 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "dogwifhat",
    name: "dogwifhat",
    symbol: "WIF",
    icon: Coins,
    price: 2.50 * USD_TO_INR,
    change24h: 14.75,
    volume24h: 500000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(2.50 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "floki",
    name: "Floki",
    symbol: "FLOKI",
    icon: Coins,
    price: 0.00017 * USD_TO_INR,
    change24h: 12.00,
    volume24h: 200000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.00017 * USD_TO_INR),
    assetType: 'Spot',
  },
  {
    id: "singularitynet",
    name: "SingularityNET",
    symbol: "AGIX",
    icon: Coins,
    price: 0.68 * USD_TO_INR,
    change24h: 9.20,
    volume24h: 150000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(0.68 * USD_TO_INR),
    assetType: 'Web3',
  },
  {
    id: "apecoin",
    name: "ApeCoin",
    symbol: "APE",
    icon: Coins,
    price: 1.0 * USD_TO_INR,
    change24h: 4.2,
    volume24h: 50000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(1.0 * USD_TO_INR),
    assetType: 'Web3',
  },
  {
    id: "uniswap",
    name: "Uniswap",
    symbol: "UNI",
    icon: Coins,
    price: 10.0 * USD_TO_INR,
    change24h: 6.2,
    volume24h: 250000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(10.0 * USD_TO_INR),
    assetType: 'Web3',
  },
  { id: 'optimism', name: 'Optimism', symbol: 'OP', icon: Coins, price: 1.76 * USD_TO_INR, change24h: 2.1, volume24h: 120000000 * USD_TO_INR, priceHistory: generatePriceHistory(1.76 * USD_TO_INR), assetType: 'Spot' },
  { id: 'arbitrum', name: 'Arbitrum', symbol: 'ARB', icon: Coins, price: 0.81 * USD_TO_INR, change24h: 3.5, volume24h: 250000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.81 * USD_TO_INR), assetType: 'Spot' },
  { id: 'aptos', name: 'Aptos', symbol: 'APT', icon: Coins, price: 6.95 * USD_TO_INR, change24h: 1.5, volume24h: 150000000 * USD_TO_INR, priceHistory: generatePriceHistory(6.95 * USD_TO_INR), assetType: 'Spot' },
  { id: 'aave', name: 'Aave', symbol: 'AAVE', icon: Coins, price: 92.5 * USD_TO_INR, change24h: -0.5, volume24h: 80000000 * USD_TO_INR, priceHistory: generatePriceHistory(92.5 * USD_TO_INR), assetType: 'Spot' },
  { id: 'near-protocol', name: 'NEAR Protocol', symbol: 'NEAR', icon: Coins, price: 5.45 * USD_TO_INR, change24h: 4.8, volume24h: 300000000 * USD_TO_INR, priceHistory: generatePriceHistory(5.45 * USD_TO_INR), assetType: 'Spot' },
  { id: 'litecoin', name: 'Litecoin', symbol: 'LTC', icon: Coins, price: 74.5 * USD_TO_INR, change24h: 1.2, volume24h: 400000000 * USD_TO_INR, priceHistory: generatePriceHistory(74.5 * USD_TO_INR), assetType: 'Spot' },
  { id: 'chainlink', name: 'Chainlink', symbol: 'LINK', icon: Coins, price: 14.2 * USD_TO_INR, change24h: 0.9, volume24h: 350000000 * USD_TO_INR, priceHistory: generatePriceHistory(14.2 * USD_TO_INR), assetType: 'Spot' },
  { id: 'algorand', name: 'Algorand', symbol: 'ALGO', icon: Coins, price: 0.13 * USD_TO_INR, change24h: -1.8, volume24h: 50000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.13 * USD_TO_INR), assetType: 'Spot' },
  { id: 'injective-protocol', name: 'Injective', symbol: 'INJ', icon: Coins, price: 23.5 * USD_TO_INR, change24h: 5.6, volume24h: 180000000 * USD_TO_INR, priceHistory: generatePriceHistory(23.5 * USD_TO_INR), assetType: 'Spot' },
  { id: 'lido-dao', name: 'Lido DAO', symbol: 'LDO', icon: Coins, price: 2.3 * USD_TO_INR, change24h: -2.3, volume24h: 90000000 * USD_TO_INR, priceHistory: generatePriceHistory(2.3 * USD_TO_INR), assetType: 'Spot' },
  { id: 'ethereum-name-service', name: 'Ethereum Name Service', symbol: 'ENS', icon: Coins, price: 24.8 * USD_TO_INR, change24h: 8.1, volume24h: 150000000 * USD_TO_INR, priceHistory: generatePriceHistory(24.8 * USD_TO_INR), assetType: 'Spot' },
  { id: 'sui', name: 'Sui', symbol: 'SUI', icon: Coins, price: 0.9 * USD_TO_INR, change24h: 2.9, volume24h: 200000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.9 * USD_TO_INR), assetType: 'Spot' },
  { id: 'immutable-x', name: 'Immutable X', symbol: 'IMX', icon: Coins, price: 1.55 * USD_TO_INR, change24h: 3.2, volume24h: 80000000 * USD_TO_INR, priceHistory: generatePriceHistory(1.55 * USD_TO_INR), assetType: 'Spot' },
  { id: 'synthetix-network-token', name: 'Synthetix', symbol: 'SNX', icon: Coins, price: 2.05 * USD_TO_INR, change24h: -1.5, volume24h: 60000000 * USD_TO_INR, priceHistory: generatePriceHistory(2.05 * USD_TO_INR), assetType: 'Spot' },
  { id: 'kava', name: 'Kava', symbol: 'KAVA', icon: Coins, price: 0.46 * USD_TO_INR, change24h: 0.8, volume24h: 25000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.46 * USD_TO_INR), assetType: 'Spot' },
  { id: 'conflux-token', name: 'Conflux', symbol: 'CFX', icon: Coins, price: 0.16 * USD_TO_INR, change24h: 1.9, volume24h: 40000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.16 * USD_TO_INR), assetType: 'Spot' },
  { id: 'blur', name: 'Blur', symbol: 'BLUR', icon: Coins, price: 0.27 * USD_TO_INR, change24h: -3.2, volume24h: 70000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.27 * USD_TO_INR), assetType: 'Spot' },
  { id: 'sei-network', name: 'Sei', symbol: 'SEI', icon: Coins, price: 0.37 * USD_TO_INR, change24h: 4.1, volume24h: 150000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.37 * USD_TO_INR), assetType: 'Spot' },
  { id: 'trust-wallet-token', name: 'Trust Wallet Token', symbol: 'TWT', icon: Coins, price: 1.1 * USD_TO_INR, change24h: 1.2, volume24h: 20000000 * USD_TO_INR, priceHistory: generatePriceHistory(1.1 * USD_TO_INR), assetType: 'Spot' },
  { id: 'ankr', name: 'Ankr', symbol: 'ANKR', icon: Coins, price: 0.03 * USD_TO_INR, change24h: 5.8, volume24h: 50000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.03 * USD_TO_INR), assetType: 'Spot' },
  { id: 'ocean-protocol', name: 'Ocean Protocol', symbol: 'OCEAN', icon: Coins, price: 0.65 * USD_TO_INR, change24h: 7.2, volume24h: 60000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.65 * USD_TO_INR), assetType: 'Spot' },
  { id: 'gmx', name: 'GMX', symbol: 'GMX', icon: Coins, price: 28.5 * USD_TO_INR, change24h: -2.1, volume24h: 30000000 * USD_TO_INR, priceHistory: generatePriceHistory(28.5 * USD_TO_INR), assetType: 'Spot' },
  { id: 'zilliqa', name: 'Zilliqa', symbol: 'ZIL', icon: Coins, price: 0.017 * USD_TO_INR, change24h: 3.3, volume24h: 25000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.017 * USD_TO_INR), assetType: 'Spot' },
  { id: 'iotex', name: 'IoTeX', symbol: 'IOTX', icon: Coins, price: 0.05 * USD_TO_INR, change24h: 4.5, volume24h: 45000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.05 * USD_TO_INR), assetType: 'Spot' },
  { id: 'qtum', name: 'Qtum', symbol: 'QTUM', icon: Coins, price: 2.55 * USD_TO_INR, change24h: 2.1, volume24h: 35000000 * USD_TO_INR, priceHistory: generatePriceHistory(2.55 * USD_TO_INR), assetType: 'Spot' },
  { id: 'loopring', name: 'Loopring', symbol: 'LRC', icon: Coins, price: 0.28 * USD_TO_INR, change24h: 6.9, volume24h: 55000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.28 * USD_TO_INR), assetType: 'Spot' },
  { id: 'harmony', name: 'Harmony', symbol: 'ONE', icon: Coins, price: 0.015 * USD_TO_INR, change24h: 1.8, volume24h: 20000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.015 * USD_TO_INR), assetType: 'Spot' },
  { id: '0x', name: '0x', symbol: 'ZRX', icon: Coins, price: 0.37 * USD_TO_INR, change24h: 8.2, volume24h: 40000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.37 * USD_TO_INR), assetType: 'Spot' },
  { id: 'bella-protocol', name: 'Bella Protocol', symbol: 'BEL', icon: Coins, price: 0.6 * USD_TO_INR, change24h: -1.1, volume24h: 5000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.6 * USD_TO_INR), assetType: 'Spot' },
  { id: 'stepn', name: 'STEPN', symbol: 'GMT', icon: Coins, price: 0.17 * USD_TO_INR, change24h: 3.6, volume24h: 30000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.17 * USD_TO_INR), assetType: 'Spot' },
  { id: 'biconomy', name: 'Biconomy', symbol: 'BICO', icon: Coins, price: 0.38 * USD_TO_INR, change24h: 2.4, volume24h: 15000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.38 * USD_TO_INR), assetType: 'Spot' },
  { id: 'ark', name: 'Ark', symbol: 'ARK', icon: Coins, price: 0.48 * USD_TO_INR, change24h: 0.5, volume24h: 3000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.48 * USD_TO_INR), assetType: 'Spot' },
  { id: 'celo', name: 'Celo', symbol: 'CELO', icon: Coins, price: 0.7 * USD_TO_INR, change24h: 2.8, volume24h: 22000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.7 * USD_TO_INR), assetType: 'Spot' },
  { id: 'storj', name: 'Storj', symbol: 'STORJ', icon: Coins, price: 0.38 * USD_TO_INR, change24h: 5.1, volume24h: 18000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.38 * USD_TO_INR), assetType: 'Spot' },
  { id: 'request-network', name: 'Request', symbol: 'REQ', icon: Coins, price: 0.11 * USD_TO_INR, change24h: 1.5, volume24h: 4000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.11 * USD_TO_INR), assetType: 'Spot' },
  { id: 'gitcoin', name: 'Gitcoin', symbol: 'GTC', icon: Coins, price: 1.0 * USD_TO_INR, change24h: -2.5, volume24h: 3000000 * USD_TO_INR, priceHistory: generatePriceHistory(1.0 * USD_TO_INR), assetType: 'Spot' },
  { id: 'aelf', name: 'aelf', symbol: 'ELF', icon: Coins, price: 0.37 * USD_TO_INR, change24h: 3.1, volume24h: 20000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.37 * USD_TO_INR), assetType: 'Spot' },
  { id: 'civic', name: 'Civic', symbol: 'CVC', icon: Coins, price: 0.11 * USD_TO_INR, change24h: 1.2, volume24h: 15000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.11 * USD_TO_INR), assetType: 'Spot' },
  { id: 'ardor', name: 'Ardor', symbol: 'ARDR', icon: Coins, price: 0.07 * USD_TO_INR, change24h: 0.8, volume24h: 2000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.07 * USD_TO_INR), assetType: 'Spot' },
  { id: 'bancor', name: 'Bancor', symbol: 'BNT', icon: Coins, price: 0.65 * USD_TO_INR, change24h: 2.3, volume24h: 8000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.65 * USD_TO_INR), assetType: 'Spot' },
  { id: 'nervos-network', name: 'Nervos Network', symbol: 'CKB', icon: Coins, price: 0.01 * USD_TO_INR, change24h: -0.5, volume24h: 12000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.01 * USD_TO_INR), assetType: 'Spot' },
  { id: 'perpetual-protocol', name: 'Perpetual Protocol', symbol: 'PERP', icon: Coins, price: 0.75 * USD_TO_INR, change24h: 4.8, volume24h: 25000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.75 * USD_TO_INR), assetType: 'Spot' },
  { id: 'band-protocol', name: 'Band Protocol', symbol: 'BAND', icon: Coins, price: 1.15 * USD_TO_INR, change24h: 3.2, volume24h: 15000000 * USD_TO_INR, priceHistory: generatePriceHistory(1.15 * USD_TO_INR), assetType: 'Spot' },
  { id: 'livepeer', name: 'Livepeer', symbol: 'LPT', icon: Coins, price: 18.5 * USD_TO_INR, change24h: 9.8, volume24h: 80000000 * USD_TO_INR, priceHistory: generatePriceHistory(18.5 * USD_TO_INR), assetType: 'Spot' },
  { id: 'stormx', name: 'StormX', symbol: 'STMX', icon: Coins, price: 0.007 * USD_TO_INR, change24h: 2.1, volume24h: 10000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.007 * USD_TO_INR), assetType: 'Spot' },
  { id: 'truefi', name: 'TrueFi', symbol: 'TRU', icon: Coins, price: 0.14 * USD_TO_INR, change24h: 12.5, volume24h: 60000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.14 * USD_TO_INR), assetType: 'Spot' },
  { id: 'cartesi', name: 'Cartesi', symbol: 'CTSI', icon: Coins, price: 0.17 * USD_TO_INR, change24h: 5.5, volume24h: 20000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.17 * USD_TO_INR), assetType: 'Spot' },
  { id: 'dent', name: 'Dent', symbol: 'DENT', icon: Coins, price: 0.001 * USD_TO_INR, change24h: -1.8, volume24h: 8000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.001 * USD_TO_INR), assetType: 'Spot' },
  { id: 'origin-protocol', name: 'Origin Protocol', symbol: 'OGN', icon: Coins, price: 0.1 * USD_TO_INR, change24h: 3.8, volume24h: 12000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.1 * USD_TO_INR), assetType: 'Spot' },
  { id: 'nkn', name: 'NKN', symbol: 'NKN', icon: Coins, price: 0.12 * USD_TO_INR, change24h: 6.2, volume24h: 18000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.12 * USD_TO_INR), assetType: 'Spot' },
  { id: 'syscoin', name: 'Syscoin', symbol: 'SYS', icon: Coins, price: 0.12 * USD_TO_INR, change24h: 2.1, volume24h: 5000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.12 * USD_TO_INR), assetType: 'Spot' },
  { id: 'selfkey', name: 'Selfkey', symbol: 'KEY', icon: Coins, price: 0.005 * USD_TO_INR, change24h: 0.9, volume24h: 2000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.005 * USD_TO_INR), assetType: 'Spot' },
  { id: 'alien-worlds', name: 'Alien Worlds', symbol: 'TLM', icon: Coins, price: 0.013 * USD_TO_INR, change24h: 4.1, volume24h: 22000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.013 * USD_TO_INR), assetType: 'Spot' },
  { id: 'barnbridge', name: 'BarnBridge', symbol: 'BOND', icon: Coins, price: 2.1 * USD_TO_INR, change24h: -3.1, volume24h: 4000000 * USD_TO_INR, priceHistory: generatePriceHistory(2.1 * USD_TO_INR), assetType: 'Spot' },
  { id: 'flamingo-finance', name: 'Flamingo', symbol: 'FLM', icon: Coins, price: 0.06 * USD_TO_INR, change24h: 1.5, volume24h: 3000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.06 * USD_TO_INR), assetType: 'Spot' },
  { id: 'alpha-finance', name: 'Alpha Venture DAO', symbol: 'ALPHA', icon: Coins, price: 0.08 * USD_TO_INR, change24h: 2.9, volume24h: 10000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.08 * USD_TO_INR), assetType: 'Spot' },
  { id: 'jasmycoin', name: 'JasmyCoin', symbol: 'JASMY', icon: Coins, price: 0.03 * USD_TO_INR, change24h: 15.1, volume24h: 250000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.03 * USD_TO_INR), assetType: 'Spot' },
  { id: 'alchemy-pay', name: 'Alchemy Pay', symbol: 'ACH', icon: Coins, price: 0.02 * USD_TO_INR, change24h: 3.3, volume24h: 30000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.02 * USD_TO_INR), assetType: 'Spot' },
  { id: 'highstreet', name: 'Highstreet', symbol: 'HIGH', icon: Coins, price: 2.0 * USD_TO_INR, change24h: 5.6, volume24h: 40000000 * USD_TO_INR, priceHistory: generatePriceHistory(2.0 * USD_TO_INR), assetType: 'Spot' },
  { id: 'mantra-dao', name: 'MANTRA', symbol: 'OM', icon: Coins, price: 0.7 * USD_TO_INR, change24h: 8.2, volume24h: 100000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.7 * USD_TO_INR), assetType: 'Spot' },
  { id: 'smooth-love-potion', name: 'Smooth Love Potion', symbol: 'SLP', icon: Coins, price: 0.003 * USD_TO_INR, change24h: 1.1, volume24h: 15000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.003 * USD_TO_INR), assetType: 'Spot' },
  { id: 'dusk-network', name: 'Dusk', symbol: 'DUSK', icon: Coins, price: 0.12 * USD_TO_INR, change24h: 2.6, volume24h: 8000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.12 * USD_TO_INR), assetType: 'Spot' },
  { id: 'coti', name: 'COTI', symbol: 'COTI', icon: Coins, price: 0.1 * USD_TO_INR, change24h: 4.8, volume24h: 25000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.1 * USD_TO_INR), assetType: 'Spot' },
  { id: 'certik', name: 'CertiK', symbol: 'CTK', icon: Coins, price: 0.8 * USD_TO_INR, change24h: 1.9, volume24h: 10000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.8 * USD_TO_INR), assetType: 'Spot' },
  { id: 'mask-network', name: 'Mask Network', symbol: 'MASK', icon: Coins, price: 2.5 * USD_TO_INR, change24h: -2.2, volume24h: 30000000 * USD_TO_INR, priceHistory: generatePriceHistory(2.5 * USD_TO_INR), assetType: 'Spot' },
  { id: 'litentry', name: 'Litentry', symbol: 'LIT', icon: Coins, price: 0.8 * USD_TO_INR, change24h: 3.4, volume24h: 6000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.8 * USD_TO_INR), assetType: 'Spot' },
  { id: 'api3', name: 'API3', symbol: 'API3', icon: Coins, price: 2.2 * USD_TO_INR, change24h: 5.1, volume24h: 20000000 * USD_TO_INR, priceHistory: generatePriceHistory(2.2 * USD_TO_INR), assetType: 'Spot' },
  { id: 'frax-share', name: 'Frax Share', symbol: 'FXS', icon: Coins, price: 3.3 * USD_TO_INR, change24h: 0.5, volume24h: 15000000 * USD_TO_INR, priceHistory: generatePriceHistory(3.3 * USD_TO_INR), assetType: 'Spot' },
  { id: 'numeraire', name: 'Numeraire', symbol: 'NMR', icon: Coins, price: 19.5 * USD_TO_INR, change24h: 2.8, volume24h: 8000000 * USD_TO_INR, priceHistory: generatePriceHistory(19.5 * USD_TO_INR), assetType: 'Spot' },
  { id: 'liquity', name: 'Liquity', symbol: 'LQTY', icon: Coins, price: 0.85 * USD_TO_INR, change24h: -0.9, volume24h: 4000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.85 * USD_TO_INR), assetType: 'Spot' },
  { id: 'prom', name: 'Prom', symbol: 'PROM', icon: Coins, price: 8.5 * USD_TO_INR, change24h: 10.1, volume24h: 30000000 * USD_TO_INR, priceHistory: generatePriceHistory(8.5 * USD_TO_INR), assetType: 'Spot' },
  { id: 'alcabone', name: 'Alcabone', symbol: 'ALCX', icon: Coins, price: 23.0 * USD_TO_INR, change24h: 1.5, volume24h: 12000000 * USD_TO_INR, priceHistory: generatePriceHistory(23.0 * USD_TO_INR), assetType: 'Spot' },
  { id: 'biswap', name: 'Biswap', symbol: 'BSW', icon: Coins, price: 0.06 * USD_TO_INR, change24h: 2.2, volume24h: 5000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.06 * USD_TO_INR), assetType: 'Spot' },
  { id: 'chromia', name: 'Chromia', symbol: 'CHR', icon: Coins, price: 0.28 * USD_TO_INR, change24h: 6.8, volume24h: 45000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.28 * USD_TO_INR), assetType: 'Spot' },
  { id: 'vanar-chain', name: 'Vanar Chain', symbol: 'VANRY', icon: Coins, price: 0.15 * USD_TO_INR, change24h: 4.2, volume24h: 25000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.15 * USD_TO_INR), assetType: 'Spot' },
  { id: 'fetch-ai', name: 'Fetch.ai', symbol: 'FET', icon: Coins, price: 1.6 * USD_TO_INR, change24h: 11.5, volume24h: 300000000 * USD_TO_INR, priceHistory: generatePriceHistory(1.6 * USD_TO_INR), assetType: 'Spot' },
  { id: 'space-id', name: 'SPACE ID', symbol: 'ID', icon: Coins, price: 0.45 * USD_TO_INR, change24h: 3.8, volume24h: 90000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.45 * USD_TO_INR), assetType: 'Spot' },
  { id: 'polymath-network', name: 'Polymath', symbol: 'POLYX', icon: Coins, price: 0.35 * USD_TO_INR, change24h: -1.1, volume24h: 15000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.35 * USD_TO_INR), assetType: 'Spot' },
  { id: 'phoenix-global', name: 'Phoenix', symbol: 'PHB', icon: Coins, price: 1.8 * USD_TO_INR, change24h: 7.9, volume24h: 120000000 * USD_TO_INR, priceHistory: generatePriceHistory(1.8 * USD_TO_INR), assetType: 'Spot' },
  { id: 'stargate-finance', name: 'Stargate Finance', symbol: 'STG', icon: Coins, price: 0.4 * USD_TO_INR, change24h: 2.1, volume24h: 40000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.4 * USD_TO_INR), assetType: 'Spot' },
  { id: 'celestia', name: 'Celestia', symbol: 'TIA', icon: Coins, price: 6.7 * USD_TO_INR, change24h: 5.3, volume24h: 200000000 * USD_TO_INR, priceHistory: generatePriceHistory(6.7 * USD_TO_INR), assetType: 'Spot' },
  { id: 'astar', name: 'Astar', symbol: 'ASTR', icon: Coins, price: 0.06 * USD_TO_INR, change24h: 4.5, volume24h: 35000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.06 * USD_TO_INR), assetType: 'Spot' },
  { id: 'beta-finance', name: 'Beta Finance', symbol: 'BETA', icon: Coins, price: 0.04 * USD_TO_INR, change24h: 1.2, volume24h: 3000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.04 * USD_TO_INR), assetType: 'Spot' },
  { id: 'osmosis', name: 'Osmosis', symbol: 'OSMO', icon: Coins, price: 0.55 * USD_TO_INR, change24h: 6.8, volume24h: 50000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.55 * USD_TO_INR), assetType: 'Spot' },
  { id: 'radicle', name: 'Radicle', symbol: 'RAD', icon: Coins, price: 1.2 * USD_TO_INR, change24h: -0.8, volume24h: 4000000 * USD_TO_INR, priceHistory: generatePriceHistory(1.2 * USD_TO_INR), assetType: 'Spot' },
  { id: 'polkastarter', name: 'Polkastarter', symbol: 'POLS', icon: Coins, price: 0.5 * USD_TO_INR, change24h: 3.1, volume24h: 8000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.5 * USD_TO_INR), assetType: 'Spot' },
  { id: 'alpine-f1-team-fan-token', name: 'Alpine F1 Team Fan Token', symbol: 'ALPINE', icon: Coins, price: 1.4 * USD_TO_INR, change24h: 0.2, volume24h: 1000000 * USD_TO_INR, priceHistory: generatePriceHistory(1.4 * USD_TO_INR), assetType: 'Spot' },
  { id: 'fc-porto', name: 'FC Porto', symbol: 'PORTO', icon: Coins, price: 1.7 * USD_TO_INR, change24h: -1.5, volume24h: 2000000 * USD_TO_INR, priceHistory: generatePriceHistory(1.7 * USD_TO_INR), assetType: 'Spot' },
  { id: 'paris-saint-germain-fan-token', name: 'Paris Saint-Germain Fan Token', symbol: 'PSG', icon: Coins, price: 3.0 * USD_TO_INR, change24h: 2.5, volume24h: 5000000 * USD_TO_INR, priceHistory: generatePriceHistory(3.0 * USD_TO_INR), assetType: 'Spot' },
  { id: 'manchester-city-fan-token', name: 'Manchester City Fan Token', symbol: 'CITY', icon: Coins, price: 2.3 * USD_TO_INR, change24h: 1.1, volume24h: 3000000 * USD_TO_INR, priceHistory: generatePriceHistory(2.3 * USD_TO_INR), assetType: 'Spot' },
  { id: 'lazio-fan-token', name: 'Lazio Fan Token', symbol: 'LAZIO', icon: Coins, price: 2.2 * USD_TO_INR, change24h: 0.8, volume24h: 2500000 * USD_TO_INR, priceHistory: generatePriceHistory(2.2 * USD_TO_INR), assetType: 'Spot' },
  { id: 'atletico-madrid', name: 'Atletico Madrid Fan Token', symbol: 'ATM', icon: Coins, price: 2.1 * USD_TO_INR, change24h: -0.2, volume24h: 1500000 * USD_TO_INR, priceHistory: generatePriceHistory(2.1 * USD_TO_INR), assetType: 'Spot' },
  { id: 'ampleforth-governance-token', name: 'Ampleforth Governance Token', symbol: 'FORTH', icon: Coins, price: 3.1 * USD_TO_INR, change24h: 4.6, volume24h: 6000000 * USD_TO_INR, priceHistory: generatePriceHistory(3.1 * USD_TO_INR), assetType: 'Spot' },
  { id: 'bonfida', name: 'Bonfida', symbol: 'FIDA', icon: Coins, price: 0.3 * USD_TO_INR, change24h: 2.9, volume24h: 10000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.3 * USD_TO_INR), assetType: 'Spot' },
  { id: 'magic-internet-money', name: 'Magic Internet Money', symbol: 'MIM', icon: Coins, price: 0.99 * USD_TO_INR, change24h: -0.2, volume24h: 20000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.99 * USD_TO_INR), assetType: 'Spot' },
  { id: 'sushi', name: 'SushiSwap', symbol: 'SUSHI', icon: Coins, price: 0.85 * USD_TO_INR, change24h: 3.8, volume24h: 35000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.85 * USD_TO_INR), assetType: 'Spot' },
  { id: 'balancer', name: 'Balancer', symbol: 'BAL', icon: Coins, price: 3.1 * USD_TO_INR, change24h: 1.7, volume24h: 12000000 * USD_TO_INR, priceHistory: generatePriceHistory(3.1 * USD_TO_INR), assetType: 'Spot' },
  { id: 'dydx', name: 'dYdX', symbol: 'DYDX', icon: Coins, price: 1.4 * USD_TO_INR, change24h: 2.5, volume24h: 60000000 * USD_TO_INR, priceHistory: generatePriceHistory(1.4 * USD_TO_INR), assetType: 'Spot' },
  { id: 'amp-token', name: 'Amp', symbol: 'AMP', icon: Coins, price: 0.005 * USD_TO_INR, change24h: 0.9, volume24h: 25000000 * USD_TO_INR, priceHistory: generatePriceHistory(0.005 * USD_TO_INR), assetType: 'Spot' },
];

export const MUTUAL_FUNDS_DATA: MutualFund[] = [
  {
      id: 'crypto-innovators-fund',
      name: 'Crypto Innovators Fund Direct-Growth',
      symbol: 'CIF',
      icon: Package,
      nav: 2457.60 * USD_TO_INR,
      navDate: '2025-06-20',
      change1d: 3.02,
      change3y: 40.57,
      rating: 'NA',
      risk: 'Very High Risk',
      tags: ['Thematic', 'Thematic'],
      minSipAmount: 1000,
      fundSize: 504000000000 * USD_TO_INR, // 50,400 Cr
      about: 'An open-ended thematic mutual fund scheme investing in a diversified portfolio of companies that are participating in and benefiting from the crypto and blockchain innovation ecosystem.',
      fundManager: {
          name: 'Jane Crypto',
          title: 'Fund Manager',
          company: 'Digital Asset Ventures',
          bio: 'Jane is a pioneer in digital asset management with over 10 years of experience in the crypto space. She specializes in quantitative analysis and on-chain metrics to drive investment decisions.'
      },
      topHoldings: [
          { name: 'Bitcoin', symbol: 'BTC', percentage: 25.50 },
          { name: 'Ethereum', symbol: 'ETH', percentage: 20.20 },
          { name: 'Solana', symbol: 'SOL', percentage: 15.80 },
          { name: 'Render', symbol: 'RNDR', percentage: 10.10 },
          { name: 'Fetch.ai', symbol: 'FET', percentage: 8.40 },
      ],
      priceHistory: generatePriceHistory(2457.60 * USD_TO_INR),
  },
  {
    id: 'blue-chip-fund',
    name: 'Blue Chip Crypto Fund',
    symbol: 'BCCF',
    icon: Package,
    nav: 1200.50 * USD_TO_INR,
    navDate: '2025-06-20',
    change1d: 1.5,
    change3y: 35.2,
    rating: '4 Stars',
    risk: 'High Risk',
    tags: ['Large Cap'],
    minSipAmount: 500,
    fundSize: 75000000000 * USD_TO_INR,
    about: 'A fund focused on established, large-market-cap cryptocurrencies to provide stable, long-term growth.',
    fundManager: {
        name: 'John Stable',
        title: 'Senior Fund Manager',
        company: 'Crypto Capital Management',
        bio: 'John has a background in traditional finance and brings a disciplined, risk-averse approach to crypto investing.'
    },
    topHoldings: [
        { name: 'Bitcoin', symbol: 'BTC', percentage: 40.00 },
        { name: 'Ethereum', symbol: 'ETH', percentage: 30.00 },
        { name: 'BNB', symbol: 'BNB', percentage: 10.00 },
        { name: 'XRP', symbol: 'XRP', percentage: 10.00 },
        { name: 'Cardano', symbol: 'ADA', percentage: 10.00 },
    ],
    priceHistory: generatePriceHistory(1200.50 * USD_TO_INR),
  },
  {
    id: 'meme-coin-fund',
    name: 'Meme Coin Mania Fund',
    symbol: 'MEME',
    icon: Package,
    nav: 50.20 * USD_TO_INR,
    navDate: '2025-06-20',
    change1d: 12.5,
    change3y: 150.7,
    rating: 'NA',
    risk: 'Very High Risk',
    tags: ['Meme', 'Small Cap'],
    minSipAmount: 100,
    fundSize: 10000000000 * USD_TO_INR,
    about: 'A high-risk, high-reward fund investing in a portfolio of popular meme coins, aiming to capture explosive growth from viral trends.',
     fundManager: {
        name: 'Chad Viral',
        title: 'Chief Meme Officer',
        company: 'Degen Investments',
        bio: 'Chad lives and breathes internet culture. His strategy involves constantly monitoring social media trends to identify the next big meme coin.'
    },
    topHoldings: [
        { name: 'Dogecoin', symbol: 'DOGE', percentage: 30.00 },
        { name: 'Shiba Inu', symbol: 'SHIB', percentage: 25.00 },
        { name: 'Pepe', symbol: 'PEPE', percentage: 20.00 },
        { name: 'dogwifhat', symbol: 'WIF', percentage: 15.00 },
        { name: 'Floki', symbol: 'FLOKI', percentage: 10.00 },
    ],
    priceHistory: generatePriceHistory(50.20 * USD_TO_INR),
  }
];

export const CRYPTO_ETFS_DATA: CryptoETF[] = [
  {
    id: 'spot-btc-etf',
    name: 'Coin Veda Bitcoin Trust',
    symbol: 'CVBTC',
    icon: BitcoinIcon,
    price: 68.50 * USD_TO_INR,
    change24h: 2.6,
    volume24h: 1500000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(68.50 * USD_TO_INR),
    issuer: 'Coin Veda Investments',
    inceptionDate: '2024-01-11',
    expenseRatio: 0.19,
    aum: 20000000000 * USD_TO_INR, // 20B
    description: 'The Coin Veda Bitcoin Trust (CVBTC) is an exchange-traded fund that directly holds Bitcoin, offering investors a regulated and straightforward way to gain exposure to the price movements of BTC without needing to own the cryptocurrency itself.',
    underlyingAssets: [
      { name: 'Bitcoin', symbol: 'BTC', weight: 100.00 }
    ],
  },
  {
    id: 'spot-eth-etf',
    name: 'Coin Veda Ethereum Trust',
    symbol: 'CVETH',
    icon: EthereumIcon,
    price: 35.80 * USD_TO_INR,
    change24h: -1.1,
    volume24h: 800000000 * USD_TO_INR,
    priceHistory: generatePriceHistory(35.80 * USD_TO_INR),
    issuer: 'Coin Veda Investments',
    inceptionDate: '2024-05-23',
    expenseRatio: 0.21,
    aum: 5000000000 * USD_TO_INR, // 5B
    description: 'The Coin Veda Ethereum Trust (CVETH) provides direct exposure to Ethereum, the second-largest cryptocurrency by market capitalization. The ETF allows investors to participate in ETH\'s potential growth through a traditional brokerage account.',
    underlyingAssets: [
      { name: 'Ethereum', symbol: 'ETH', weight: 100.00 }
    ],
  },
];

export const ADDITIONAL_FUNDS_ETFS_DATA: CryptoETF[] = [
  { id: 'ibit', name: 'iShares Bitcoin Trust ETF', symbol: 'IBIT', icon: Package, price: 41.20 * USD_TO_INR, change24h: 1.5, volume24h: 2100000000 * USD_TO_INR, priceHistory: generatePriceHistory(41.2 * USD_TO_INR), issuer: 'iShares', inceptionDate: '2024-01-11', expenseRatio: 0.25, aum: 20000000000 * USD_TO_INR, description: 'Spot Bitcoin Exposure.', underlyingAssets: [{ name: 'Bitcoin', symbol: 'BTC', weight: 100 }] },
  { id: 'fbtc', name: 'Fidelity Wise Origin Bitcoin Fund', symbol: 'FBTC', icon: Package, price: 62.50 * USD_TO_INR, change24h: 1.4, volume24h: 1800000000 * USD_TO_INR, priceHistory: generatePriceHistory(62.5 * USD_TO_INR), issuer: 'Fidelity', inceptionDate: '2024-01-11', expenseRatio: 0.25, aum: 15000000000 * USD_TO_INR, description: 'Spot Bitcoin by Fidelity.', underlyingAssets: [{ name: 'Bitcoin', symbol: 'BTC', weight: 100 }] },
  { id: 'arkb', name: 'ARK 21Shares Bitcoin ETF', symbol: 'ARKB', icon: Package, price: 71.30 * USD_TO_INR, change24h: 1.8, volume24h: 900000000 * USD_TO_INR, priceHistory: generatePriceHistory(71.3 * USD_TO_INR), issuer: 'ARK/21Shares', inceptionDate: '2024-01-11', expenseRatio: 0.21, aum: 10000000000 * USD_TO_INR, description: 'Bitcoin focus.', underlyingAssets: [{ name: 'Bitcoin', symbol: 'BTC', weight: 100 }] },
  { id: 'bitb', name: 'Bitwise Bitcoin ETF Trust', symbol: 'BITB', icon: Package, price: 39.80 * USD_TO_INR, change24h: 1.6, volume24h: 700000000 * USD_TO_INR, priceHistory: generatePriceHistory(39.8 * USD_TO_INR), issuer: 'Bitwise', inceptionDate: '2024-01-11', expenseRatio: 0.20, aum: 8000000000 * USD_TO_INR, description: 'Bitcoin exposure.', underlyingAssets: [{ name: 'Bitcoin', symbol: 'BTC', weight: 100 }] },
  { id: 'bkch', name: 'Global X Blockchain ETF', symbol: 'BKCH', icon: Package, price: 35.10 * USD_TO_INR, change24h: 2.1, volume24h: 50000000 * USD_TO_INR, priceHistory: generatePriceHistory(35.1 * USD_TO_INR), issuer: 'Global X', inceptionDate: '2021-07-13', expenseRatio: 0.50, aum: 500000000 * USD_TO_INR, description: 'Broader blockchain/crypto infrastructure exposure.', underlyingAssets: [] },
  { id: 'dapp', name: 'VanEck Digital Transformation ETF', symbol: 'DAPP', icon: Package, price: 28.40 * USD_TO_INR, change24h: 2.5, volume24h: 40000000 * USD_TO_INR, priceHistory: generatePriceHistory(28.4 * USD_TO_INR), issuer: 'VanEck', inceptionDate: '2021-04-14', expenseRatio: 0.50, aum: 400000000 * USD_TO_INR, description: 'Digital asset / blockchain themed.', underlyingAssets: [] },
  { id: 'fdig', name: 'Fidelity Crypto Industry &amp; Digital Payments ETF', symbol: 'FDIG', icon: Package, price: 45.90 * USD_TO_INR, change24h: 1.9, volume24h: 60000000 * USD_TO_INR, priceHistory: generatePriceHistory(45.9 * USD_TO_INR), issuer: 'Fidelity', inceptionDate: '2022-04-21', expenseRatio: 0.39, aum: 600000000 * USD_TO_INR, description: 'Crypto industry + digital payments theme.', underlyingAssets: [] },
  { id: 'bitw', name: 'Bitwise 10 Crypto Index Fund', symbol: 'BITW', icon: Package, price: 32.70 * USD_TO_INR, change24h: 3.2, volume24h: 100000000 * USD_TO_INR, priceHistory: generatePriceHistory(32.7 * USD_TO_INR), issuer: 'Bitwise', inceptionDate: '2017-11-22', expenseRatio: 2.50, aum: 1000000000 * USD_TO_INR, description: 'Index of top cryptos.', underlyingAssets: [] },
  { id: 'bits', name: 'Global X Blockchain &amp; Bitcoin Strategy ETF', symbol: 'BITS', icon: Package, price: 55.60 * USD_TO_INR, change24h: 2.8, volume24h: 30000000 * USD_TO_INR, priceHistory: generatePriceHistory(55.6 * USD_TO_INR), issuer: 'Global X', inceptionDate: '2021-11-16', expenseRatio: 0.65, aum: 300000000 * USD_TO_INR, description: 'Strategy: futures + blockchain + bitcoin.', underlyingAssets: [] },
  { id: 'iblc', name: 'iShares Blockchain &amp; Tech ETF', symbol: 'IBLC', icon: Package, price: 25.80 * USD_TO_INR, change24h: 1.2, volume24h: 20000000 * USD_TO_INR, priceHistory: generatePriceHistory(25.8 * USD_TO_INR), issuer: 'iShares', inceptionDate: '2022-04-26', expenseRatio: 0.47, aum: 200000000 * USD_TO_INR, description: 'Companies involved in blockchain tech (international component).', underlyingAssets: [] },
  { id: 'hbte', name: 'Harvest Bitcoin Leaders Enhanced Income ETF', symbol: 'HBTE', icon: Package, price: 18.20 * USD_TO_INR, change24h: 1.1, volume24h: 15000000 * USD_TO_INR, priceHistory: generatePriceHistory(18.2 * USD_TO_INR), issuer: 'Harvest', inceptionDate: '2021-01-20', expenseRatio: 0.85, aum: 150000000 * USD_TO_INR, description: 'Bitcoin exposure via Canadian listed product.', underlyingAssets: [] },
  { id: 'btcc', name: 'Purpose Bitcoin ETF', symbol: 'BTCC', icon: Package, price: 10.50 * USD_TO_INR, change24h: 1.3, volume24h: 500000000 * USD_TO_INR, priceHistory: generatePriceHistory(10.5 * USD_TO_INR), issuer: 'Purpose', inceptionDate: '2021-02-18', expenseRatio: 1.00, aum: 3000000000 * USD_TO_INR, description: 'Bitcoin exposure via Canadian product.', underlyingAssets: [] },
  { id: 'btci', name: 'NEOS ETF Trust Bitcoin High Income ETF', symbol: 'BTCI', icon: Package, price: 50.10 * USD_TO_INR, change24h: 0.9, volume24h: 25000000 * USD_TO_INR, priceHistory: generatePriceHistory(50.1 * USD_TO_INR), issuer: 'NEOS', inceptionDate: '2022-08-17', expenseRatio: 0.68, aum: 250000000 * USD_TO_INR, description: 'Bitcoin exposure via U.S product.', underlyingAssets: [] },
  { id: 'btcc-u', name: 'Purpose Bitcoin ETF Non-Currency Hedged USD', symbol: 'BTCC.U', icon: Package, price: 10.45 * USD_TO_INR, change24h: 1.3, volume24h: 50000000 * USD_TO_INR, priceHistory: generatePriceHistory(10.45 * USD_TO_INR), issuer: 'Purpose', inceptionDate: '2021-02-18', expenseRatio: 1.00, aum: 300000000 * USD_TO_INR, description: 'Variation of Bitcoin ETF in Canada.', underlyingAssets: [] },
  { id: 'ssd', name: 'CoinShares Physical Bitcoin ETP', symbol: 'SSD', icon: Package, price: 85.00 * USD_TO_INR, change24h: 1.4, volume24h: 120000000 * USD_TO_INR, priceHistory: generatePriceHistory(85 * USD_TO_INR), issuer: 'CoinShares', inceptionDate: '2021-01-19', expenseRatio: 0.98, aum: 1000000000 * USD_TO_INR, description: 'European crypto-backed ETP.', underlyingAssets: [] },
  { id: 'xbtp', name: 'iShares Bitcoin ETP Switzerland', symbol: 'XBTP', icon: Package, price: 92.00 * USD_TO_INR, change24h: 1.5, volume24h: 80000000 * USD_TO_INR, priceHistory: generatePriceHistory(92 * USD_TO_INR), issuer: 'iShares', inceptionDate: '2022-11-29', expenseRatio: 0.25, aum: 500000000 * USD_TO_INR, description: 'Swiss domicile crypto ETP.', underlyingAssets: [] },
  { id: 'bchc', name: 'European Crypto Blockchain ETF', symbol: 'BCHC', icon: Package, price: 42.10 * USD_TO_INR, change24h: 2.2, volume24h: 35000000 * USD_TO_INR, priceHistory: generatePriceHistory(42.1 * USD_TO_INR), issuer: 'Various', inceptionDate: '2021-09-15', expenseRatio: 0.60, aum: 350000000 * USD_TO_INR, description: 'Crypto blockchain theme in EU.', underlyingAssets: [] },
  { id: 'gldc', name: 'Grayscale Digital Large Cap Fund', symbol: 'GLDC', icon: Package, price: 15.30 * USD_TO_INR, change24h: 2.0, volume24h: 200000000 * USD_TO_INR, priceHistory: generatePriceHistory(15.3 * USD_TO_INR), issuer: 'Grayscale', inceptionDate: '2019-10-18', expenseRatio: 2.50, aum: 2000000000 * USD_TO_INR, description: 'Multi-crypto fund (Bitcoin, Ethereum, etc) under upcoming new listing standards.', underlyingAssets: [] },
  { id: 'hash', name: 'Hashdex Bitcoin ETF - USD DIS', symbol: 'HASH', icon: Package, price: 65.40 * USD_TO_INR, change24h: 1.7, volume24h: 400000000 * USD_TO_INR, priceHistory: generatePriceHistory(65.4 * USD_TO_INR), issuer: 'Hashdex', inceptionDate: '2023-01-10', expenseRatio: 0.90, aum: 1200000000 * USD_TO_INR, description: 'Bitcoin exposure via US listed product but international manager.', underlyingAssets: [] },
  { id: 'nci', name: 'Nasdaq Crypto Index ETF', symbol: 'NCI', icon: Package, price: 75.00 * USD_TO_INR, change24h: 2.3, volume24h: 90000000 * USD_TO_INR, priceHistory: generatePriceHistory(75 * USD_TO_INR), issuer: 'Nasdaq/Valkyrie', inceptionDate: '2021-06-22', expenseRatio: 0.80, aum: 800000000 * USD_TO_INR, description: 'Index of cryptocurrencies / crypto-linked exposure.', underlyingAssets: [] },
];


export const NEWS_ARTICLES: NewsArticle[] = [
    {
      id: 1,
      title: "Bitcoin ETFs See Record Inflows as Institutions Pile In",
      source: "CryptoNews Daily",
      published: "2 hours ago",
      url: "#",
      content: "Spot Bitcoin ETFs have experienced a surge in capital inflows this week, with major financial institutions increasing their holdings. Analysts suggest this renewed institutional interest is a primary driver behind Bitcoin's recent price rally towards the $70,000 mark. The trend indicates a growing acceptance of cryptocurrency as a legitimate asset class among traditional investors."
    },
    {
      id: 2,
      title: "Ethereum's 'Pectra' Upgrade: What to Expect",
      source: "ETH Hub",
      published: "8 hours ago",
      url: "#",
      content: "The Ethereum community is buzzing with anticipation for the upcoming 'Pectra' network upgrade. This upgrade is expected to introduce several key improvements, including EIP-3074, which will enhance smart contract capabilities and user experience by allowing externally owned accounts (EOAs) to delegate control to a contract. This could simplify transactions and enable new DeFi functionalities."
    },
    {
      id: 3,
      title: "Meme Coin Mania Cools Down, But Dogecoin Holds Strong",
      source: "The Coin Telegraph",
      published: "1 day ago",
      url: "#",
      content: "The recent frenzy around meme coins appears to be subsiding, with many smaller tokens seeing significant price corrections. However, established players like Dogecoin have shown resilience, maintaining a relatively stable price and strong community support. This suggests a potential flight to 'quality' even within the highly volatile meme coin sector."
    },
     {
      id: 4,
      title: "Regulatory Landscape for Crypto Shifts in Europe",
      source: "Global Finance",
      published: "2 days ago",
      url: "#",
      content: "European Union regulators are finalizing the implementation of the Markets in Crypto-Assets (MiCA) framework. The new rules aim to provide a clear legal structure for crypto service providers and issuers, enhancing consumer protection and market integrity. While some in the industry have raised concerns about compliance costs, the overall sentiment is that regulatory clarity will foster long-term growth and stability in the European crypto market."
    }
  ];


