import { BitcoinIcon, DogecoinIcon, EthereumIcon } from "@/components/icons";
import { CryptoCurrency, MutualFund, NewsArticle, CryptoETF } from "./types";
import { Coins, Package } from "lucide-react";

const generatePriceHistory = (base: number, days = 365) => {
  const history = [];
  let currentPrice = base;
  for (let i = 0; i < days; i++) {
    const date = new Date(Date.now() - (days - 1 - i) * 24 * 60 * 60 * 1000);
    // Add hourly fluctuations for the last day
    if (i === days - 1) {
      let hourlyPrice = history[history.length - 1]?.value || base * (1 + (Math.random() - 0.5) * 0.1);
      for (let j = 0; j < 24; j++) {
        history.push({
          time: new Date(date.getTime() - (23 - j) * 60 * 60 * 1000).toISOString(),
          value: hourlyPrice,
        });
        hourlyPrice *= (1 + (Math.random() - 0.49) * 0.02); // Tighter fluctuation for hours
      }
    } else {
       history.push({
        time: date.toISOString(),
        value: currentPrice,
      });
      currentPrice *= (1 + (Math.random() - 0.49) * 0.1); // Fluctuate by up to 10% daily
    }
  }
  return history;
};


export const INITIAL_CRYPTO_DATA: CryptoCurrency[] = [
  {
    id: "bitcoin",
    name: "Bitcoin",
    symbol: "BTC",
    icon: BitcoinIcon,
    price: 68134.32,
    change24h: 2.5,
    volume24h: 34500000000,
    priceHistory: generatePriceHistory(68134.32),
    assetType: 'Spot',
  },
  {
    id: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    icon: EthereumIcon,
    price: 3567.89,
    change24h: -1.2,
    volume24h: 18200000000,
    priceHistory: generatePriceHistory(3567.89),
    assetType: 'Spot',
  },
  {
    id: 'tether',
    name: 'Tether',
    symbol: 'USDT',
    icon: Coins,
    price: 1.00,
    change24h: 0.00,
    volume24h: 50000000000,
    priceHistory: generatePriceHistory(1.00),
    assetType: 'Spot',
  },
  {
    id: 'binancecoin',
    name: 'BNB',
    symbol: 'BNB',
    icon: Coins,
    price: 570.00,
    change24h: 0.89,
    volume24h: 1500000000,
    priceHistory: generatePriceHistory(570.00),
    assetType: 'Spot',
  },
  {
    id: 'usd-coin',
    name: 'USD Coin',
    symbol: 'USDC',
    icon: Coins,
    price: 1.00,
    change24h: 0.00,
    volume24h: 5000000000,
    priceHistory: generatePriceHistory(1.00),
    assetType: 'Spot',
  },
  {
    id: "cardano",
    name: "Cardano",
    symbol: "ADA",
    icon: Coins,
    price: 0.38,
    change24h: -2.17,
    volume24h: 350000000,
    priceHistory: generatePriceHistory(0.38),
    assetType: 'Spot',
  },
  {
    id: "solana",
    name: "Solana",
    symbol: "SOL",
    icon: Coins,
    price: 150.0,
    change24h: 5.5,
    volume24h: 2000000000,
    priceHistory: generatePriceHistory(150.0),
    assetType: 'Spot',
  },
  {
    id: "ripple",
    name: "XRP",
    symbol: "XRP",
    icon: Coins,
    price: 0.47,
    change24h: 2.13,
    volume24h: 1200000000,
    priceHistory: generatePriceHistory(0.47),
    assetType: 'Spot',
  },
  {
    id: 'terra-luna',
    name: 'Terra',
    symbol: 'LUNA',
    icon: Coins,
    price: 0.43,
    change24h: 1.5,
    volume24h: 30000000,
    priceHistory: generatePriceHistory(0.43),
    assetType: 'Spot',
  },
  {
    id: 'polkadot',
    name: 'Polkadot',
    symbol: 'DOT',
    icon: Coins,
    price: 5.88,
    change24h: 3.1,
    volume24h: 200000000,
    priceHistory: generatePriceHistory(5.88),
    assetType: 'Spot',
  },
  {
    id: "dogecoin",
    name: "Dogecoin",
    symbol: "DOGE",
    icon: DogecoinIcon,
    price: 0.12,
    change24h: 5.8,
    volume24h: 2100000000,
    priceHistory: generatePriceHistory(0.12),
    assetType: 'Spot',
  },
  {
    id: 'avalanche-2',
    name: 'Avalanche',
    symbol: 'AVAX',
    icon: Coins,
    price: 25.45,
    change24h: 4.2,
    volume24h: 400000000,
    priceHistory: generatePriceHistory(25.45),
    assetType: 'Spot',
  },
  {
    id: 'binance-usd',
    name: 'Binance USD',
    symbol: 'BUSD',
    icon: Coins,
    price: 1.00,
    change24h: 0.0,
    volume24h: 3000000000,
    priceHistory: generatePriceHistory(1.00),
    assetType: 'Spot',
  },
  {
    id: 'matic-network',
    name: 'Polygon',
    symbol: 'MATIC',
    icon: Coins,
    price: 0.57,
    change24h: 2.8,
    volume24h: 300000000,
    priceHistory: generatePriceHistory(0.57),
    assetType: 'Spot',
  },
  {
    id: "shiba-inu",
    name: "Shiba Inu",
    symbol: "SHIB",
    icon: Coins,
    price: 0.000017,
    change24h: 3.7,
    volume24h: 300000000,
    priceHistory: generatePriceHistory(0.000017),
    assetType: 'Spot',
  },
  {
    id: 'terrausd',
    name: 'TerraUSD',
    symbol: 'UST',
    icon: Coins,
    price: 0.018,
    change24h: -1.0,
    volume24h: 10000000,
    priceHistory: generatePriceHistory(0.018),
    assetType: 'Spot',
  },
  {
    id: 'crypto-com-chain',
    name: 'Crypto.com Coin',
    symbol: 'CRO',
    icon: Coins,
    price: 0.09,
    change24h: 1.2,
    volume24h: 15000000,
    priceHistory: generatePriceHistory(0.09),
    assetType: 'Spot',
  },
  {
    id: 'wrapped-bitcoin',
    name: 'Wrapped Bitcoin',
    symbol: 'WBTC',
    icon: Coins,
    price: 68130.00,
    change24h: 2.5,
    volume24h: 200000000,
    priceHistory: generatePriceHistory(68130.00),
    assetType: 'Spot',
  },
  {
    id: 'dai',
    name: 'Dai',
    symbol: 'DAI',
    icon: Coins,
    price: 1.00,
    change24h: 0.0,
    volume24h: 400000000,
    priceHistory: generatePriceHistory(1.00),
    assetType: 'Spot',
  },
  {
    id: 'cosmos',
    name: 'Cosmos',
    symbol: 'ATOM',
    icon: Coins,
    price: 6.95,
    change24h: 3.5,
    volume24h: 150000000,
    priceHistory: generatePriceHistory(6.95),
    assetType: 'Spot',
  },
  {
    id: 'ftx-token',
    name: 'FTX Token',
    symbol: 'FTT',
    icon: Coins,
    price: 1.45,
    change24h: -0.5,
    volume24h: 20000000,
    priceHistory: generatePriceHistory(1.45),
    assetType: 'Spot',
  },
  {
    id: "tron",
    name: "TRON",
    symbol: "TRX",
    icon: Coins,
    price: 0.11,
    change24h: 2.56,
    volume24h: 400000000,
    priceHistory: generatePriceHistory(0.11),
    assetType: 'Spot',
  },
  {
    id: 'bitcoin-cash',
    name: 'Bitcoin Cash',
    symbol: 'BCH',
    icon: Coins,
    price: 388.0,
    change24h: 1.8,
    volume24h: 300000000,
    priceHistory: generatePriceHistory(388.0),
    assetType: 'Spot',
  },
  {
    id: 'fantom',
    name: 'Fantom',
    symbol: 'FTM',
    icon: Coins,
    price: 0.60,
    change24h: 7.2,
    volume24h: 150000000,
    priceHistory: generatePriceHistory(0.60),
    assetType: 'Spot',
  },
  {
    id: 'stellar',
    name: 'Stellar',
    symbol: 'XLM',
    icon: Coins,
    price: 0.09,
    change24h: 1.1,
    volume24h: 70000000,
    priceHistory: generatePriceHistory(0.09),
    assetType: 'Spot',
  },
  {
    id: "decentraland",
    name: "Decentraland",
    symbol: "MANA",
    icon: Coins,
    price: 0.33,
    change24h: 2.5,
    volume24h: 45000000,
    priceHistory: generatePriceHistory(0.33),
    assetType: 'Web3',
  },
  {
    id: 'hedera-hashgraph',
    name: 'Hedera',
    symbol: 'HBAR',
    icon: Coins,
    price: 0.078,
    change24h: 4.8,
    volume24h: 50000000,
    priceHistory: generatePriceHistory(0.078),
    assetType: 'Spot',
  },
  {
    id: 'bitcoin-bep2',
    name: 'Bitcoin BEP2',
    symbol: 'BTCB',
    icon: Coins,
    price: 68100.0,
    change24h: 2.4,
    volume24h: 10000000,
    priceHistory: generatePriceHistory(68100.0),
    assetType: 'Spot',
  },
  {
    id: 'internet-computer',
    name: 'Internet Computer',
    symbol: 'ICP',
    icon: Coins,
    price: 8.30,
    change24h: 6.1,
    volume24h: 100000000,
    priceHistory: generatePriceHistory(8.30),
    assetType: 'Spot',
  },
  {
    id: 'unus-sed-leo',
    name: 'UNUS SED LEO',
    symbol: 'LEO',
    icon: Coins,
    price: 5.75,
    change24h: 0.1,
    volume24h: 2000000,
    priceHistory: generatePriceHistory(5.75),
    assetType: 'Spot',
  },
  {
    id: "the-sandbox",
    name: "The Sandbox",
    symbol: "SAND",
    icon: Coins,
    price: 0.33,
    change24h: 3.1,
    volume24h: 60000000,
    priceHistory: generatePriceHistory(0.33),
    assetType: 'Web3',
  },
  {
    id: 'ethereum-classic',
    name: 'Ethereum Classic',
    symbol: 'ETC',
    icon: Coins,
    price: 23.50,
    change24h: 1.5,
    volume24h: 200000000,
    priceHistory: generatePriceHistory(23.50),
    assetType: 'Spot',
  },
  {
    id: 'vechain',
    name: 'VeChain',
    symbol: 'VET',
    icon: Coins,
    price: 0.026,
    change24h: 3.9,
    volume24h: 50000000,
    priceHistory: generatePriceHistory(0.026),
    assetType: 'Spot',
  },
  {
    id: 'tezos',
    name: 'Tezos',
    symbol: 'XTZ',
    icon: Coins,
    price: 0.78,
    change24h: 2.2,
    volume24h: 30000000,
    priceHistory: generatePriceHistory(0.78),
    assetType: 'Spot',
  },
  {
    id: 'axie-infinity',
    name: 'Axie Infinity',
    symbol: 'AXS',
    icon: Coins,
    price: 6.20,
    change24h: 5.5,
    volume24h: 80000000,
    priceHistory: generatePriceHistory(6.20),
    assetType: 'Spot',
  },
  {
    id: 'filecoin',
    name: 'Filecoin',
    symbol: 'FIL',
    icon: Coins,
    price: 4.40,
    change24h: 4.1,
    volume24h: 150000000,
    priceHistory: generatePriceHistory(4.40),
    assetType: 'Spot',
  },
  {
    id: 'elrond-erd-2',
    name: 'Elrond',
    symbol: 'EGLD',
    icon: Coins,
    price: 30.00,
    change24h: 6.8,
    volume24h: 50000000,
    priceHistory: generatePriceHistory(30.00),
    assetType: 'Spot',
  },
  {
    id: 'klay-token',
    name: 'Klaytn',
    symbol: 'KLAY',
    icon: Coins,
    price: 0.16,
    change24h: 1.9,
    volume24h: 20000000,
    priceHistory: generatePriceHistory(0.16),
    assetType: 'Spot',
  },
  {
    id: 'helium',
    name: 'Helium',
    symbol: 'HNT',
    icon: Coins,
    price: 3.40,
    change24h: 8.2,
    volume24h: 15000000,
    priceHistory: generatePriceHistory(3.40),
    assetType: 'Spot',
  },
  {
    id: 'theta-token',
    name: 'Theta Network',
    symbol: 'THETA',
    icon: Coins,
    price: 1.60,
    change24h: 7.5,
    volume24h: 60000000,
    priceHistory: generatePriceHistory(1.60),
    assetType: 'Spot',
  },
  {
    id: 'maker',
    name: 'Maker',
    symbol: 'MKR',
    icon: Coins,
    price: 2375.00,
    change24h: 0.5,
    volume24h: 90000000,
    priceHistory: generatePriceHistory(2375.00),
    assetType: 'Spot',
  },
  {
    id: 'flow',
    name: 'Flow',
    symbol: 'FLOW',
    icon: Coins,
    price: 0.64,
    change24h: 4.3,
    volume24h: 40000000,
    priceHistory: generatePriceHistory(0.64),
    assetType: 'Spot',
  },
  {
    id: 'the-graph',
    name: 'The Graph',
    symbol: 'GRT',
    icon: Coins,
    price: 0.22,
    change24h: 9.9,
    volume24h: 100000000,
    priceHistory: generatePriceHistory(0.22),
    assetType: 'Spot',
  },
  {
    id: 'pancakeswap-token',
    name: 'PancakeSwap',
    symbol: 'CAKE',
    icon: Coins,
    price: 2.2,
    change24h: 1.8,
    volume24h: 40000000,
    priceHistory: generatePriceHistory(2.2),
    assetType: 'Web3',
  },
  {
    id: 'bittorrent-2',
    name: 'BitTorrent (New)',
    symbol: 'BTT',
    icon: Coins,
    price: 0.00000088,
    change24h: 2.1,
    volume24h: 300000000,
    priceHistory: generatePriceHistory(0.00000088),
    assetType: 'Spot',
  },
  {
    id: 'stacks',
    name: 'Stacks',
    symbol: 'STX',
    icon: Coins,
    price: 2.05,
    change24h: 10.5,
    volume24h: 120000000,
    priceHistory: generatePriceHistory(2.05),
    assetType: 'Spot',
  },
  {
    id: 'bitcoin-sv',
    name: 'Bitcoin SV',
    symbol: 'BSV',
    icon: Coins,
    price: 45.50,
    change24h: -2.5,
    volume24h: 40000000,
    priceHistory: generatePriceHistory(45.50),
    assetType: 'Spot',
  },
  {
    id: 'curve-dao-token',
    name: 'Curve DAO Token',
    symbol: 'CRV',
    icon: Coins,
    price: 0.34,
    change24h: 15.2,
    volume24h: 80000000,
    priceHistory: generatePriceHistory(0.34),
    assetType: 'Spot',
  },
  {
    id: 'enjincoin',
    name: 'Enjin Coin',
    symbol: 'ENJ',
    icon: Coins,
    price: 0.20,
    change24h: 6.3,
    volume24h: 25000000,
    priceHistory: generatePriceHistory(0.20),
    assetType: 'Spot',
  },
  {
    id: 'true-usd',
    name: 'TrueUSD',
    symbol: 'TUSD',
    icon: Coins,
    price: 0.99,
    change24h: -0.1,
    volume24h: 50000000,
    priceHistory: generatePriceHistory(0.99),
    assetType: 'Spot',
  },
  {
    id: 'kucoin-shares',
    name: 'KuCoin Token',
    symbol: 'KCS',
    icon: Coins,
    price: 9.80,
    change24h: 0.8,
    volume24h: 1000000,
    priceHistory: generatePriceHistory(9.80),
    assetType: 'Spot',
  },
  {
    id: 'kusama',
    name: 'Kusama',
    symbol: 'KSM',
    icon: Coins,
    price: 24.00,
    change24h: 3.2,
    volume24h: 15000000,
    priceHistory: generatePriceHistory(24.00),
    assetType: 'Spot',
  },
  {
    id: 'ecash',
    name: 'eCash',
    symbol: 'XEC',
    icon: Coins,
    price: 0.000032,
    change24h: 5.1,
    volume24h: 20000000,
    priceHistory: generatePriceHistory(0.000032),
    assetType: 'Spot',
  },
  {
    id: 'huobi-token',
    name: 'Huobi Token',
    symbol: 'HT',
    icon: Coins,
    price: 0.52,
    change24h: -1.2,
    volume24h: 5000000,
    priceHistory: generatePriceHistory(0.52),
    assetType: 'Spot',
  },
  {
    id: 'neo',
    name: 'Neo',
    symbol: 'NEO',
    icon: Coins,
    price: 11.40,
    change24h: 4.5,
    volume24h: 40000000,
    priceHistory: generatePriceHistory(11.40),
    assetType: 'Spot',
  },
  {
    id: 'gala',
    name: 'Gala',
    symbol: 'GALA',
    icon: Coins,
    price: 0.028,
    change24h: 8.8,
    volume24h: 90000000,
    priceHistory: generatePriceHistory(0.028),
    assetType: 'Spot',
  },
  {
    id: 'thorchain',
    name: 'THORChain',
    symbol: 'RUNE',
    icon: Coins,
    price: 4.15,
    change24h: 7.1,
    volume24h: 180000000,
    priceHistory: generatePriceHistory(4.15),
    assetType: 'Spot',
  },
  {
    id: 'arweave',
    name: 'Arweave',
    symbol: 'AR',
    icon: Coins,
    price: 29.00,
    change24h: 12.3,
    volume24h: 70000000,
    priceHistory: generatePriceHistory(29.00),
    assetType: 'Spot',
  },
  {
    id: 'convex-finance',
    name: 'Convex Finance',
    symbol: 'CVX',
    icon: Coins,
    price: 3.00,
    change24h: -3.5,
    volume24h: 5000000,
    priceHistory: generatePriceHistory(3.00),
    assetType: 'Spot',
  },
  {
    id: 'zcash',
    name: 'Zcash',
    symbol: 'ZEC',
    icon: Coins,
    price: 20.20,
    change24h: 1.1,
    volume24h: 30000000,
    priceHistory: generatePriceHistory(20.20),
    assetType: 'Spot',
  },
  {
    id: 'quant-network',
    name: 'Quant',
    symbol: 'QNT',
    icon: Coins,
    price: 76.00,
    change24h: 2.8,
    volume24h: 20000000,
    priceHistory: generatePriceHistory(76.00),
    assetType: 'Spot',
  },
  {
    id: 'oasis-network',
    name: 'Oasis Network',
    symbol: 'ROSE',
    icon: Coins,
    price: 0.09,
    change24h: 6.7,
    volume24h: 25000000,
    priceHistory: generatePriceHistory(0.09),
    assetType: 'Spot',
  },
  {
    id: 'nexo',
    name: 'NEXO',
    symbol: 'NEXO',
    icon: Coins,
    price: 1.19,
    change24h: 0.5,
    volume24h: 5000000,
    priceHistory: generatePriceHistory(1.19),
    assetType: 'Spot',
  },
  {
    id: 'chiliz',
    name: 'Chiliz',
    symbol: 'CHZ',
    icon: Coins,
    price: 0.08,
    change24h: 11.2,
    volume24h: 90000000,
    priceHistory: generatePriceHistory(0.08),
    assetType: 'Spot',
  },
  {
    id: 'symbol',
    name: 'Symbol',
    symbol: 'XYM',
    icon: Coins,
    price: 0.02,
    change24h: 1.3,
    volume24h: 1000000,
    priceHistory: generatePriceHistory(0.02),
    assetType: 'Spot',
  },
  {
    id: 'kadena',
    name: 'Kadena',
    symbol: 'KDA',
    icon: Coins,
    price: 0.58,
    change24h: 3.3,
    volume24h: 5000000,
    priceHistory: generatePriceHistory(0.58),
    assetType: 'Spot',
  },
  {
    id: 'dash',
    name: 'Dash',
    symbol: 'DASH',
    icon: Coins,
    price: 24.00,
    change24h: 2.1,
    volume24h: 40000000,
    priceHistory: generatePriceHistory(24.00),
    assetType: 'Spot',
  },
  {
    id: 'waves',
    name: 'Waves',
    symbol: 'WAVES',
    icon: Coins,
    price: 2.40,
    change24h: 13.5,
    volume24h: 150000000,
    priceHistory: generatePriceHistory(2.40),
    assetType: 'Spot',
  },
  {
    id: 'paxos-standard',
    name: 'Pax Dollar',
    symbol: 'USDP',
    icon: Coins,
    price: 1.00,
    change24h: 0.0,
    volume24h: 5000000,
    priceHistory: generatePriceHistory(1.00),
    assetType: 'Spot',
  },
  {
    id: 'mina-protocol',
    name: 'Mina',
    symbol: 'MINA',
    icon: Coins,
    price: 0.54,
    change24h: 7.9,
    volume24h: 30000000,
    priceHistory: generatePriceHistory(0.54),
    assetType: 'Spot',
  },
  {
    id: 'nem',
    name: 'NEM',
    symbol: 'XEM',
    icon: Coins,
    price: 0.015,
    change24h: -2.1,
    volume24h: 2000000,
    priceHistory: generatePriceHistory(0.015),
    assetType: 'Spot',
  },
  {
    id: 'theta-fuel',
    name: 'Theta Fuel',
    symbol: 'TFUEL',
    icon: Coins,
    price: 0.076,
    change24h: 5.8,
    volume24h: 20000000,
    priceHistory: generatePriceHistory(0.076),
    assetType: 'Spot',
  },
  {
    id: 'yearn-finance',
    name: 'yearn.finance',
    symbol: 'YFI',
    icon: Coins,
    price: 5850.00,
    change24h: 1.2,
    volume24h: 25000000,
    priceHistory: generatePriceHistory(5850.00),
    assetType: 'Spot',
  },
  {
    id: 'bora',
    name: 'BORA',
    symbol: 'BORA',
    icon: Coins,
    price: 0.10,
    change24h: 0.9,
    volume24h: 1000000,
    priceHistory: generatePriceHistory(0.10),
    assetType: 'Spot',
  },
  {
    id: 'decred',
    name: 'Decred',
    symbol: 'DCR',
    icon: Coins,
    price: 16.00,
    change24h: -0.5,
    volume24h: 2000000,
    priceHistory: generatePriceHistory(16.00),
    assetType: 'Spot',
  },
  {
    id: 'compound-governance-token',
    name: 'Compound',
    symbol: 'COMP',
    icon: Coins,
    price: 49.00,
    change24h: 3.9,
    volume24h: 40000000,
    priceHistory: generatePriceHistory(49.00),
    assetType: 'Spot',
  },
  {
    id: 'secret',
    name: 'Secret',
    symbol: 'SCRT',
    icon: Coins,
    price: 0.31,
    change24h: 4.1,
    volume24h: 3000000,
    priceHistory: generatePriceHistory(0.31),
    assetType: 'Spot',
  },
  {
    id: 'holotoken',
    name: 'Holo',
    symbol: 'HOT',
    icon: Coins,
    price: 0.0018,
    change24h: 2.7,
    volume24h: 15000000,
    priceHistory: generatePriceHistory(0.0018),
    assetType: 'Spot',
  },
  {
    id: '1inch',
    name: '1inch',
    symbol: '1INCH',
    icon: Coins,
    price: 0.40,
    change24h: 8.1,
    volume24h: 40000000,
    priceHistory: generatePriceHistory(0.40),
    assetType: 'Spot',
  },
  {
    id: 'render-token',
    name: 'Render Token',
    symbol: 'RNDR',
    icon: Coins,
    price: 7.70,
    change24h: 9.5,
    volume24h: 200000000,
    priceHistory: generatePriceHistory(7.70),
    assetType: 'Spot',
  },
  {
    id: "notcoin",
    name: "Notcoin",
    symbol: "NOT",
    icon: Coins,
    price: 0.015,
    change24h: 25.00,
    volume24h: 1000000000,
    priceHistory: generatePriceHistory(0.015),
    assetType: 'Spot',
  },
  {
    id: "pepe",
    name: "Pepe",
    symbol: "PEPE",
    icon: Coins,
    price: 0.000011,
    change24h: 18.87,
    volume24h: 800000000,
    priceHistory: generatePriceHistory(0.000011),
    assetType: 'Spot',
  },
  {
    id: "dogwifhat",
    name: "dogwifhat",
    symbol: "WIF",
    icon: Coins,
    price: 2.50,
    change24h: 14.75,
    volume24h: 500000000,
    priceHistory: generatePriceHistory(2.50),
    assetType: 'Spot',
  },
  {
    id: "floki",
    name: "Floki",
    symbol: "FLOKI",
    icon: Coins,
    price: 0.00017,
    change24h: 12.00,
    volume24h: 200000000,
    priceHistory: generatePriceHistory(0.00017),
    assetType: 'Spot',
  },
  {
    id: "singularitynet",
    name: "SingularityNET",
    symbol: "AGIX",
    icon: Coins,
    price: 0.68,
    change24h: 9.20,
    volume24h: 150000000,
    priceHistory: generatePriceHistory(0.68),
    assetType: 'Web3',
  },
  {
    id: "apecoin",
    name: "ApeCoin",
    symbol: "APE",
    icon: Coins,
    price: 1.0,
    change24h: 4.2,
    volume24h: 50000000,
    priceHistory: generatePriceHistory(1.0),
    assetType: 'Web3',
  },
  {
    id: "uniswap",
    name: "Uniswap",
    symbol: "UNI",
    icon: Coins,
    price: 10.0,
    change24h: 6.2,
    volume24h: 250000000,
    priceHistory: generatePriceHistory(10.0),
    assetType: 'Web3',
  },
];

export const MUTUAL_FUNDS_DATA: MutualFund[] = [
  {
      id: 'crypto-innovators-fund',
      name: 'Crypto Innovators Fund Direct-Growth',
      symbol: 'CIF',
      icon: Package,
      nav: 2457.60,
      navDate: '2025-06-20',
      change1d: 3.02,
      change3y: 40.57,
      rating: 'NA',
      risk: 'Very High Risk',
      tags: ['Thematic', 'Thematic'],
      minSipAmount: 1000,
      fundSize: 504000000000, // 50,400 Cr
      about: 'An open-ended thematic mutual fund scheme investing in a diversified portfolio of companies that are participating in and benefiting from the crypto and blockchain innovation ecosystem.',
      fundManager: {
          name: 'Jane Crypto',
          title: 'Fund Manager',
          company: 'Digital Asset Ventures',
          bio: 'Jane is a pioneer in digital asset management with over 10 years of experience in the crypto space. She specializes in quantitative analysis and on-chain metrics to drive investment decisions.'
      },
      topHoldings: [
          { name: 'Bitcoin', symbol: 'BTC', percentage: 25.50 },
          { name: 'Ethereum', symbol: 'ETH', percentage: 20.20 },
          { name: 'Solana', symbol: 'SOL', percentage: 15.80 },
          { name: 'Render', symbol: 'RNDR', percentage: 10.10 },
          { name: 'Fetch.ai', symbol: 'FET', percentage: 8.40 },
      ],
      priceHistory: generatePriceHistory(2457.60),
  },
  {
    id: 'blue-chip-fund',
    name: 'Blue Chip Crypto Fund',
    symbol: 'BCCF',
    icon: Package,
    nav: 1200.50,
    navDate: '2025-06-20',
    change1d: 1.5,
    change3y: 35.2,
    rating: '4 Stars',
    risk: 'High Risk',
    tags: ['Large Cap'],
    minSipAmount: 500,
    fundSize: 75000000000,
    about: 'A fund focused on established, large-market-cap cryptocurrencies to provide stable, long-term growth.',
    fundManager: {
        name: 'John Stable',
        title: 'Senior Fund Manager',
        company: 'Crypto Capital Management',
        bio: 'John has a background in traditional finance and brings a disciplined, risk-averse approach to crypto investing.'
    },
    topHoldings: [
        { name: 'Bitcoin', symbol: 'BTC', percentage: 40.00 },
        { name: 'Ethereum', symbol: 'ETH', percentage: 30.00 },
        { name: 'BNB', symbol: 'BNB', percentage: 10.00 },
        { name: 'XRP', symbol: 'XRP', percentage: 10.00 },
        { name: 'Cardano', symbol: 'ADA', percentage: 10.00 },
    ],
    priceHistory: generatePriceHistory(1200.50),
  },
  {
    id: 'meme-coin-fund',
    name: 'Meme Coin Mania Fund',
    symbol: 'MEME',
    icon: Package,
    nav: 50.20,
    navDate: '2025-06-20',
    change1d: 12.5,
    change3y: 150.7,
    rating: 'NA',
    risk: 'Very High Risk',
    tags: ['Meme', 'Small Cap'],
    minSipAmount: 100,
    fundSize: 10000000000,
    about: 'A high-risk, high-reward fund investing in a portfolio of popular meme coins, aiming to capture explosive growth from viral trends.',
     fundManager: {
        name: 'Chad Viral',
        title: 'Chief Meme Officer',
        company: 'Degen Investments',
        bio: 'Chad lives and breathes internet culture. His strategy involves constantly monitoring social media trends to identify the next big meme coin.'
    },
    topHoldings: [
        { name: 'Dogecoin', symbol: 'DOGE', percentage: 30.00 },
        { name: 'Shiba Inu', symbol: 'SHIB', percentage: 25.00 },
        { name: 'Pepe', symbol: 'PEPE', percentage: 20.00 },
        { name: 'dogwifhat', symbol: 'WIF', percentage: 15.00 },
        { name: 'Floki', symbol: 'FLOKI', percentage: 10.00 },
    ],
    priceHistory: generatePriceHistory(50.20),
  }
];

export const CRYPTO_ETFS_DATA: CryptoETF[] = [
  {
    id: 'spot-btc-etf',
    name: 'SIM Bitcoin Trust',
    symbol: 'SIMBTC',
    icon: BitcoinIcon,
    price: 68.50,
    change24h: 2.6,
    volume24h: 1500000000,
    priceHistory: generatePriceHistory(68.50),
    issuer: 'SIM Investments',
    inceptionDate: '2024-01-11',
    expenseRatio: 0.19,
    aum: 20000000000, // 20B
    description: 'The SIM Bitcoin Trust (SIMBTC) is an exchange-traded fund that directly holds Bitcoin, offering investors a regulated and straightforward way to gain exposure to the price movements of BTC without needing to own the cryptocurrency itself.',
    underlyingAssets: [
      { name: 'Bitcoin', symbol: 'BTC', weight: 100.00 }
    ],
  },
  {
    id: 'spot-eth-etf',
    name: 'SIM Ethereum Trust',
    symbol: 'SIMETH',
    icon: EthereumIcon,
    price: 35.80,
    change24h: -1.1,
    volume24h: 800000000,
    priceHistory: generatePriceHistory(35.80),
    issuer: 'SIM Investments',
    inceptionDate: '2024-05-23',
    expenseRatio: 0.21,
    aum: 5000000000, // 5B
    description: 'The SIM Ethereum Trust (SIMETH) provides direct exposure to Ethereum, the second-largest cryptocurrency by market capitalization. The ETF allows investors to participate in ETH\'s potential growth through a traditional brokerage account.',
    underlyingAssets: [
      { name: 'Ethereum', symbol: 'ETH', weight: 100.00 }
    ],
  },
];


export const NEWS_ARTICLES: NewsArticle[] = [
    {
      id: 1,
      title: "Bitcoin ETFs See Record Inflows as Institutions Pile In",
      source: "CryptoNews Daily",
      published: "2 hours ago",
      url: "#",
      content: "Spot Bitcoin ETFs have experienced a surge in capital inflows this week, with major financial institutions increasing their holdings. Analysts suggest this renewed institutional interest is a primary driver behind Bitcoin's recent price rally towards the $70,000 mark. The trend indicates a growing acceptance of cryptocurrency as a legitimate asset class among traditional investors."
    },
    {
      id: 2,
      title: "Ethereum's 'Pectra' Upgrade: What to Expect",
      source: "ETH Hub",
      published: "8 hours ago",
      url: "#",
      content: "The Ethereum community is buzzing with anticipation for the upcoming 'Pectra' network upgrade. This upgrade is expected to introduce several key improvements, including EIP-3074, which will enhance smart contract capabilities and user experience by allowing externally owned accounts (EOAs) to delegate control to a contract. This could simplify transactions and enable new DeFi functionalities."
    },
    {
      id: 3,
      title: "Meme Coin Mania Cools Down, But Dogecoin Holds Strong",
      source: "The Coin Telegraph",
      published: "1 day ago",
      url: "#",
      content: "The recent frenzy around meme coins appears to be subsiding, with many smaller tokens seeing significant price corrections. However, established players like Dogecoin have shown resilience, maintaining a relatively stable price and strong community support. This suggests a potential flight to 'quality' even within the highly volatile meme coin sector."
    },
     {
      id: 4,
      title: "Regulatory Landscape for Crypto Shifts in Europe",
      source: "Global Finance",
      published: "2 days ago",
      url: "#",
      content: "European Union regulators are finalizing the implementation of the Markets in Crypto-Assets (MiCA) framework. The new rules aim to provide a clear legal structure for crypto service providers and issuers, enhancing consumer protection and market integrity. While some in the industry have raised concerns about compliance costs, the overall sentiment is that regulatory clarity will foster long-term growth and stability in the European crypto market."
    }
  ];
