
export interface TradingPair {
  exchange: 'Binance' | 'Coinbase';
  pair: string;
  baseAsset: string;
  quoteAsset: string;
  status: 'TRADING' | 'active';
}

export const spotPairs: TradingPair[] = [
  { exchange: 'Binance', pair: 'BTCUSDT', baseAsset: 'BTC', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'ETHUSDT', baseAsset: 'ETH', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'BNBUSDT', baseAsset: 'BNB', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'SOLUSDT', baseAsset: 'SOL', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'XRPUSDT', baseAsset: 'XRP', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Coinbase', pair: 'BTC-USD', baseAsset: 'BTC', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'ETH-USD', baseAsset: 'ETH', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'SOL-USD', baseAsset: 'SOL', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'XRP-USD', baseAsset: 'XRP', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Binance', pair: 'ADAUSDT', baseAsset: 'ADA', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'DOGEUSDT', baseAsset: 'DOGE', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'AVAXUSDT', baseAsset: 'AVAX', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'DOTUSDT', baseAsset: 'DOT', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'LINKUSDT', baseAsset: 'LINK', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'MATICUSDT', baseAsset: 'MATIC', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'TRXUSDT', baseAsset: 'TRX', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'LTCUSDT', baseAsset: 'LTC', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'SHIBUSDT', baseAsset: 'SHIB', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'OPUSDT', baseAsset: 'OP', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'ARBUSDT', baseAsset: 'ARB', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'APTUSDT', baseAsset: 'APT', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'SANDUSDT', baseAsset: 'SAND', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'AAVEUSDT', baseAsset: 'AAVE', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'NEARUSDT', baseAsset: 'NEAR', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Coinbase', pair: 'ADA-USD', baseAsset: 'ADA', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'AVAX-USD', baseAsset: 'AVAX', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'DOGE-USD', baseAsset: 'DOGE', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'MATIC-USD', baseAsset: 'MATIC', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'DOT-USD', baseAsset: 'DOT', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'LINK-USD', baseAsset: 'LINK', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'LTC-USD', baseAsset: 'LTC', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'SHIB-USD', baseAsset: 'SHIB', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'UNI-USD', baseAsset: 'UNI', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'AAVE-USD', baseAsset: 'AAVE', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'ATOM-USD', baseAsset: 'ATOM', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'FIL-USD', baseAsset: 'FIL', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'NEAR-USD', baseAsset: 'NEAR', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'XLM-USD', baseAsset: 'XLM', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'ALGO-USD', baseAsset: 'ALGO', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'SAND-USD', baseAsset: 'SAND', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'APT-USD', baseAsset: 'APT', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'ARB-USD', baseAsset: 'ARB', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'OP-USD', baseAsset: 'OP', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'GRT-USD', baseAsset: 'GRT', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'CRV-USD', baseAsset: 'CRV', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'MKR-USD', baseAsset: 'MKR', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'RENDER-USD', baseAsset: 'RENDER', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'INJ-USD', baseAsset: 'INJ', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'LDO-USD', baseAsset: 'LDO', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'PEPE-USD', baseAsset: 'PEPE', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Binance', pair: 'ETCUSDT', baseAsset: 'ETC', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'FILUSDT', baseAsset: 'FIL', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'ATOMUSDT', baseAsset: 'ATOM', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'ICPUSDT', baseAsset: 'ICP', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'VETUSDT', baseAsset: 'VET', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'EGLDUSDT', baseAsset: 'EGLD', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'RENDERUSDT', baseAsset: 'RENDER', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'GRTUSDT', baseAsset: 'GRT', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'CHZUSDT', baseAsset: 'CHZ', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'CRVUSDT', baseAsset: 'CRV', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'INJUSDT', baseAsset: 'INJ', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'LDOUSDT', baseAsset: 'LDO', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'MKRUSDT', baseAsset: 'MKR', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'FTMUSDT', baseAsset: 'FTM', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'THETAUSDT', baseAsset: 'THETA', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'HBARUSDT', baseAsset: 'HBAR', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'XLMUSDT', baseAsset: 'XLM', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'ALGOUSDT', baseAsset: 'ALGO', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'SUIUSDT', baseAsset: 'SUI', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'RNDRUSDT', baseAsset: 'RNDR', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'FLOWUSDT', baseAsset: 'FLOW', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'MANAUSDT', baseAsset: 'MANA', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'SNXUSDT', baseAsset: 'SNX', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'IMXUSDT', baseAsset: 'IMX', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'GALAUSDT', baseAsset: 'GALA', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'STXUSDT', baseAsset: 'STX', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'DYDXUSDT', baseAsset: 'DYDX', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'KAVAUSDT', baseAsset: 'KAVA', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'CFXUSDT', baseAsset: 'CFX', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Binance', pair: 'SEIUSDT', baseAsset: 'SEI', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: 'Coinbase', pair: 'ENS-USD', baseAsset: 'ENS', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'AXS-USD', baseAsset: 'AXS', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'IMX-USD', baseAsset: 'IMX', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'FLOW-USD', baseAsset: 'FLOW', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'GALA-USD', baseAsset: 'GALA', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'SUI-USD', baseAsset: 'SUI', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'SNX-USD', baseAsset: 'SNX', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'DYDX-USD', baseAsset: 'DYDX', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'FTM-USD', baseAsset: 'FTM', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'HBAR-USD', baseAsset: 'HBAR', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'EGLD-USD', baseAsset: 'EGLD', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'VET-USD', baseAsset: 'VET', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'STX-USD', baseAsset: 'STX', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'RUNE-USD', baseAsset: 'RUNE', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'KAVA-USD', baseAsset: 'KAVA', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'CHZ-USD', baseAsset: 'CHZ', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'CFX-USD', baseAsset: 'CFX', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'BLUR-USD', baseAsset: 'BLUR', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'SEI-USD', baseAsset: 'SEI', quoteAsset: 'USD', status: 'active' },
  { exchange: 'Coinbase', pair: 'APE-USD', baseAsset: 'APE', quoteAsset: 'USD', status: 'active' },
];

export const futuresPairs: TradingPair[] = [
  { exchange: 'Binance', pair: 'BTCUSDT', baseAsset: 'BTC', quoteAsset: 'USDT', status: 'TRADING' },
  { exchange: "Binance", pair: "ETHUSDT", baseAsset: "ETH", quoteAsset: "USDT", status: "TRADING" },
  { exchange: "Binance", pair: "SOLUSDT", baseAsset: "SOL", quoteAsset: "USDT", status: "TRADING" },
  { exchange: "Binance", pair: "XRPUSDT", baseAsset: "XRP", quoteAsset: "USDT", status: "TRADING" },
  { exchange: "Coinbase", pair: "BTC-USD", baseAsset: "BTC", quoteAsset: "USD", status: "active" },
  { exchange: "Coinbase", pair: "ETH-USD", baseAsset: "ETH", quoteAsset: "USD", status: "active" },
  { exchange: "Coinbase", pair: "SOL-USD", baseAsset: "SOL", quoteAsset: "USD", status: "active" },
];
